### ISSUE TITLE
multi_gpu_train_r3det.

### ISSUE THREAD

**Issue by MelodyCanoe** [Thinklab-SJTU/R3Det_Tensorflow#1]
I don't find 'multi_gpu_train_r3det.py' ,'test_dota_r3det.py'.Can u provide them ? Thanks !

**Comment by yangxue0827** [comment]
Will open source in February @MelodyCanoe

**Comment by MelodyCanoe** [comment]
Thank you very much！------------------ 原始邮件 ------------------
发件人: "yangxue"<notifications@github.com>
发送时间: 2020年1月8日(星期三) 下午4:00
收件人: "SJTU-Thinklab-Det/R3Det_Tensorflow"<R3Det_Tensorflow@noreply.github.com>;
抄送: "MelodyCanoe"<gandeqiao@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [SJTU-Thinklab-Det/R3Det_Tensorflow] multi_gpu_train_r3det. (#1)



Will open source in February @MelodyCanoe
 
&mdash;

**Comment by yangxue0827** [comment]
The code is released.
