### ISSUE TITLE
test_dota_r3det_ms.py测试结果疑问

### ISSUE THREAD

**Issue by GuitarZhang** [Thinklab-SJTU/R3Det_Tensorflow#100]
你好，
1.我用test_dota_r3det_ms.py及你提供的76.23 model，去对DOTA数据集val里面的P0003.png测试，但是得到的结果有很多的ship,但是图片里面没有ship，全是大车或者小车。能检出来400多个物体，ship占了至少1/3。如果显示图片，设置了显示阈值为0.4，这样剩下100多个物体，还是会有10个左右ship。这是正常的吗？
2.请问你用DOTAsever去测试的时候，提供的数据有经过阈值处理吗？就是score大于多少，才会写入txt文件？
非常感谢！

**Comment by yangxue0827** [comment]
76.2这个权重好像出了点问题，可能是我代码修改过的原因，测试可视化有问题，建议自己重新训练一下。或者在[RotationDetection](https://github.com/yangxue0827/RotationDetection)里使用相应的baseline权重

**Comment by GuitarZhang** [comment]
好的，谢谢作者。
另外还请问，我利用修改过的tools/test_hrsc2016_r3det.py去计算DOTA val数据集的map，70.66那个模型，计算出来map有84，这是不是跟DOTA server的计算方式不太一样导致的？

**Comment by yangxue0827** [comment]
我的结果是测试集的，你应该算的是验证集的，训练集和验证集我都训练过。

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/98327329-40a3e780-202e-11eb-96ed-e1cbb768606a.png)

**Comment by GuitarZhang** [comment]
就是训练的时候训练集合验证集都用了是吗？这样这个结果就能理解了。
