### ISSUE TITLE
训练不收敛的问题

### ISSUE THREAD

**Issue by 1172066589** [Thinklab-SJTU/R3Det_Tensorflow#101]
你好，请问一下。我在训练的时候total loss最后在0.8左右震荡了。能询问一下，可能是哪些原因造成的吗

**Comment by yangxue0827** [comment]
loss多大才算收敛？

**Comment by 1172066589** [comment]
就看您的实验结果，最后的loss不是降到0.1，0.2左右吗

**Comment by yangxue0827** [comment]
图是以前的，这个代码一直在维护更新，你只要训练次数达到，loss趋于平缓就可以，不用在乎loss的具体数值。
不然完全可以吧loss weight设置缩小十倍到0.08，具体大小没有意义，也不能衡量模型的好坏。
