### ISSUE TITLE
模型训练时间问题

### ISSUE THREAD

**Issue by Conearth** [Thinklab-SJTU/R3Det_Tensorflow#107]
我用的4张1080 训练的，训完108万个step大概需要50个小时，这正常吗？请问您训练模型的平均时长是多少？
我每张卡显存占用7个G，但利用率都不太高，在30～80%浮动。

**Comment by yangxue0827** [comment]
正常的，不过你训练到13个epoch就行（70.2w），也就是第一次学习率下降完的最近一次保存的权重。
