### ISSUE TITLE
Restore model......

### ISSUE THREAD

**Issue by s-s-wang** [Thinklab-SJTU/R3Det_Tensorflow#108]
When I use the MobilenetV2 to train the model, I spent eight hours restore the model. Would it have taken me a long time to restore the model, or was there any code in the program that needed to be changed? Thanks for your reading.

**Comment by yangxue0827** [comment]
Please check the tfrecoed. High probability is that data cannot be read from tfrecord.

**Comment by HelloLidakang** [comment]
作者您好，我们的图片和labelTxt可以读入data_crop.py中，并在DOTA1.0子文件夹下重新生成了images、labelTxt. 但一直重复在restore model。我们的GPU只有一块，该修改那个地方呢？麻烦您解答一下吧

**Comment by yangxue0827** [comment]
这说明你的tfrecord是空的，没有数据读出来。检查一下tfrecord的生成

**Comment by HelloLidakang** [comment]
请问是查看DOTA_train.tfrecord是否是空的吗？

**Comment by yangxue0827** [comment]
嗯，生成tfrecord会有进度条显示的，如果没有那就是路径不正确

**Comment by HelloLidakang** [comment]
可是运行python convert_data_to_tfrecord.py 他在规定的路径下生成.tfrecord文件，但文件里面是空的。这是为什么呢？ 前面运行的步骤都没有报错

**Comment by yangxue0827** [comment]
单步调试，检查数据路径

**Comment by HelloLidakang** [comment]
好的，我试一下。多谢作者耐心指导！

**Comment by HelloLidakang** [comment]
作者，您好。上面那个问题解决了，跑通python multi_gpu_train_r3det.py后，出现2020-11-23 21:59:03: global_step:1440  current_step:1440
per_cost_time:0.188s
refine_reg_loss:0.000
total_losses:1.854
refine_cls_loss:0.036
refine_cls_loss_stage3:0.000
cls_loss:1.132
refine_reg_loss_stage3:0.000
reg_loss:0.686
，就代表处于训练中了吧？
