### ISSUE TITLE
关于第一步python setup.py build_ext --inplace出现问题

### ISSUE THREAD

**Issue by zixuan19971114** [Thinklab-SJTU/R3Det_Tensorflow#109]
您好！我在第一步python setup.py build_ext --inplace就出现了问题，出现了乱码bbox.c:9511:11: error: 鈥�PyThreadState {aka struct _ts}鈥� has no member named 鈥�exc_type鈥�
     tstate->exc_type = local_type;
的同时，报错是error: command 'gcc' failed with exit status 1
因为是初学者，所以这个问题确实很困扰我~希望可以得到解答，谢谢您！

**Comment by Kongsea** [comment]
How did you fix it finally?@zixuan19971114

**Comment by zixuan19971114** [comment]
> How did you fix it finally?@zixuan19971114

The GPU I used to run this model before was 3090.When there is a problem, I change it to 2080TI.Other Settings did not change, but the problem was fixed.I guess the previous error was due to the configuration of the environment.

**Comment by Kongsea** [comment]
I just clone the code and build it, then the error was raised...

I delete all c files in $PATH_ROOT/libs/box_utils/cython_utils and run `python setup.py build_ext --inplace` in it and succeed.
But  when run the same command in `$PATH_ROOT/libs/box_utils/`, the same error was raised and there are no c files in it.
I don't know how to fix it now...

**Comment by Kongsea** [comment]
@yangxue0827 Could you please give me some advice. Thank you.

**Comment by ThePaperFish** [comment]
Please delete every `.c` `.so` `.cpp` files in `box_utils` & `cython_utils`. 
`python setup.py build_ext --inplace` command will generate those following files. 

after that you will get an error regards to `->exc_`, just replace `->exc_` to `->curexc_` can fix the error.
