### ISSUE TITLE
restore model

### ISSUE THREAD

**Issue by HelloLidakang** [Thinklab-SJTU/R3Det_Tensorflow#110]
作者您好，我们的图片和labelTxt可以读入data_crop.py中，并在DOTA1.0子文件夹下重新生成了images、labelTxt. 但一直重复在restore model。我们的GPU只有一块，该修改那个地方呢？麻烦您解答一下吧

**Comment by HelloLidakang** [comment]
训练的是mobilenet

**Comment by gev222599** [comment]
@HelloLidakang 请问你解决了相关问题吗，我也和你们遇到了同样的问题，但是找不到解决方法
