### ISSUE TITLE
Video Memory

### ISSUE THREAD

**Issue by j18567260** [Thinklab-SJTU/R3Det_Tensorflow#112]
作者你好，我目前只有一块3080显卡，它只有10GB显存，在训练过程中经常报显存分配状态，影响速度，请问我该修改代码哪个地方呢？我看到Batch_size默认已经是1了

**Comment by j18567260** [comment]
我应该降低哪个参数，去减少显存占用呢？

**Comment by yangxue0827** [comment]
图片大小，backbone...
我记得使用resnet50，800*800只需要7g多的显存，你跑的什么配置。

**Comment by j18567260** [comment]
> 图片大小，backbone...
> 我记得使用resnet50，800*800只需要7g多的显存，你跑的什么配置。

多谢你，基于resnet50的模型我训练出来了，但不知道为什么检测不到对象，测试结果文件中一个数据也没有。

**Comment by yangxue0827** [comment]
说明训练有问题，比如nan了等，原因很多，需要你自己根据自己的情况去分析调参数。
