### ISSUE TITLE
pretrained-weights

### ISSUE THREAD

**Issue by StevenqrYang** [Thinklab-SJTU/R3Det_Tensorflow#113]
为何使用您的模型进行训练时，显示调用的checkpoint文件是pretrained-weights下的文件，而不是您提供的R3Det文件。

**Comment by yangxue0827** [comment]
训练不就是使用pretrained-weights下的文件

**Comment by StevenqrYang** [comment]
不好意思，写错了，是测试时

**Comment by yangxue0827** [comment]
你下载的权重摆放位置呢，参考下图摆放：
![image](https://user-images.githubusercontent.com/29257168/101736701-cb30a880-3afe-11eb-8a97-bb0c260ffb6e.png)

**Comment by yangxue0827** [comment]
然后cfgs有没有选择对应的，主要是根据下面参数加载对应模型的
![image](https://user-images.githubusercontent.com/29257168/101736824-f9ae8380-3afe-11eb-8a3b-370fb4686744.png)

**Comment by StevenqrYang** [comment]
非常感谢
