### ISSUE TITLE
请问运行test后会有什么样的输出

### ISSUE THREAD

**Issue by Baymaaax** [Thinklab-SJTU/R3Det_Tensorflow#114]
我在成功运行test后没有找到输出在哪里

**Comment by rw1995** [comment]
请问是解决的，遇到同样的问题

**Comment by Baymaaax** [comment]
放置训练好的模型参数要保留外层括号，路径如"\output\trained_weights\RetinaNet_DOTA_R3Det_2x_20191108\checkpoint文件"
