### ISSUE TITLE
使用dota/test数据集检测不到任何物体可能是什么原因造成的？

### ISSUE THREAD

**Issue by Baymaaax** [Thinklab-SJTU/R3Det_Tensorflow#115]
我使用的这组参数：
R3Det | ResNet50_v1d 600->800 | DOTA1.0 trainval | DOTA1.0 test | 70.66
并且在cfgs.py中做了修改，请问还需要在其他位置作修改吗？

**Comment by yangxue0827** [comment]
检查下载的训练好的权重的摆放位置，并使用对应版本的cfgs。

**Comment by Baymaaax** [comment]
我再试一下，非常感谢您的回复
