### ISSUE TITLE
Annotation Type

### ISSUE THREAD

**Issue by yashwant07** [Thinklab-SJTU/R3Det_Tensorflow#116]
Can i use a polygon or instance segmentation if no, then i have instance segments based annotation if I convert into the required format that will help or not?

**Comment by yangxue0827** [comment]
You just need to turn to four points

**Comment by yashwant07** [comment]
I have 4 points polygon I can create a tfrecord using that so which training file I can use for the training model on my dataset?

**Comment by yangxue0827** [comment]
Yes, you can.

**Comment by yashwant07** [comment]
thanks!
