### ISSUE TITLE
测试时如何处理图片？

### ISSUE THREAD

**Issue by MioChiu** [Thinklab-SJTU/R3Det_Tensorflow#118]
您好，在训练DOTA数据集时会用data_crop.py将图片割成子图来进行训练，那么在测试时对测试图片要怎样处理呢？也是割成子图送进网络inference再把结果合并吗？

**Comment by MioChiu** [comment]
您好，我在test_dota_ms.py里看到分割图片的代码了，但是没有找到合并子图结果的代码，您可以告诉我这部分在哪儿嘛:)

**Comment by yangxue0827** [comment]
https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/master/tools/test_dota_ms.py#L130

然后后面还进行了nms操作
