### ISSUE TITLE
opencv错误

### ISSUE THREAD

**Issue by zhangjia3** [Thinklab-SJTU/R3Det_Tensorflow#119]
你好非常感谢您在该方向的工作，我在运行时出现了以下OpenCV错误，想请教一下
OpenCV Error: Assertion failed (intersection.size() <= 8) in rotatedRectangleIntersection, file /io/opencv/modules/imgproc/src/intersection.cpp, line 247

**Comment by yangxue0827** [comment]
好像把opencv升级到最新就好了

**Comment by yangxue0827** [comment]
https://github.com/Thinklab-SJTU/R3Det_Tensorflow/issues/117
