### ISSUE TITLE
用eval或者inference运行不出bbox的问题

### ISSUE THREAD

**Issue by vron8632** [Thinklab-SJTU/R3Det_Tensorflow#12]
我的环境配置、预训练模型用的都是文档里要求的，但是eval或者inference的时候bbox是空的，rpnbox还都有值。请问是什么原因呢？

**Comment by vron8632** [comment]
补充一下提问，是不是因为权重文件的问题呢？论文提供的ImageNet的Resnet权重是不能出结果的吧？

**Comment by yangxue0827** [comment]
请下载训练好的权重测试：https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/master/MODEL_ZOO.md
@vron8632

**Comment by yangxue0827** [comment]
https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/master/output/trained_weights/README.md

@vron8632

**Comment by tcxia** [comment]
@yangxue0827 按照这个权重文件运行，也没出来结果

**Comment by lw230** [comment]
test文件中False 改成True 就行了parser.add_argument('--show_box', '-s', default=False,
                        action='store_true')
