### ISSUE TITLE
Adapting Anchors & Angles for Extremely Skewed Dataset

### ISSUE THREAD

**Issue by dilpreetsingh** [Thinklab-SJTU/R3Det_Tensorflow#121]
Hey,

My dataset has extremely skewed aspect ratios, so for example the width of an object could be 800px, whilst the height may only be 20px. So the objects are extremely wide and thin, and generally run across from left to right of the image. 

I was wondering whether/if I need to adapt the ANCHOR_RATIOS and ANCHOR_ANGLES (in libs/configs/cfgs.py) to my own dataset? Or should I use the default ratios?

Any other recommendations/tips for dealing with such skewed objects?

**Comment by yangxue0827** [comment]
anchor free based method may be more suitable
