### ISSUE TITLE
got mAP of 0.52 in dotav1?

### ISSUE THREAD

**Issue by nishit01** [Thinklab-SJTU/R3Det_Tensorflow#125]
Hi, Thanks for open sourcing your code. I followed the steps for the setup

However, I am getting mAP of 0.52 for the training image in DOTAv1 dataset

Following are the steps I followed for testing the trained images and calculating mAP 

1. Downloaded the [model - R3Det](https://drive.google.com/file/d/1GkpiSPN-cAnvDISk5d4kjrV3Tqti_mbj/view) + all the pre-trained weights `https://github.com/Thinklab-SJTU/R3Det_Tensorflow#download-model` and placed under data/pretrained_weights
2. Performed Testing on the train images by following the command in this section `https://github.com/Thinklab-SJTU/R3Det_Tensorflow#test` and placed img_dir pointing to the train images
3. Results obtained under dota_res (starting with Tas1_<classname>) are then evaluated with dota_evaluation_task1.py from DOTA_devkit 

Kindly let me know if I am making some mistakes and how to rectify it.
Thanks

**Comment by yangxue0827** [comment]
You need train the model if you noly use pretrain weight  or  you should download the trained model before directly test the image

**Comment by nishit01** [comment]
Hi @yangxue0827  thanks for responding ... I have downloaded the trained model and placed under .../R3Det_Tensorflow/output/trained_weights/RetinaNet_DOTA_R3Det_4x_20200819 and [this](https://drive.google.com/file/d/1GkpiSPN-cAnvDISk5d4kjrV3Tqti_mbj/view?usp=sharing) link is the one I used for pretrained weights and the pretrained weights are placed under .../R3Det_Tensorflow/data/pretrained_weights

Any mistake I am making?

**Comment by yangxue0827** [comment]
You need choose the copy corresponding [cfgs_res152_dota_r3det_v3.py](https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/master/libs/configs/DOTA1.0/r3det/cfgs_res152_dota_r3det_v3.py) to cfgs.py

**Comment by nishit01** [comment]
ok, I am running this now ... the GPU is not completely getting utilized ... can you help me with that? it seems to me only 1 image is getting processed at a time ... I am not that familiar with TensorFlow, pardon me if I am incorrect?

**Comment by yangxue0827** [comment]
use yangxue0827/RotationDetection instead
