### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by yzk-lab** [Thinklab-SJTU/R3Det_Tensorflow#126]
作者，你好！我请教一下为什么我训练一到200步就出现这个图片中的问题呢？我用的单块2080Ti.
![image](https://user-images.githubusercontent.com/41197028/112944380-52b12e80-9165-11eb-9546-7386e3412c51.png)
l另外，我用另外一台服务器的1080Ti跑python multi_gpu_train_r3det.py 程序不报错，但是一直卡在restore model 那里是什么原因呢?麻烦指教了！谢谢！

**Comment by yangxue0827** [comment]
你这个可能是用的大模型的配置文件训练的，导致显存不够用。

一直卡在restore model的原因多半是制作的tfrecord是空的，读不出数据，建议查看一下tfrecord的大小是不是0.

**Comment by yzk-lab** [comment]
> 你这个可能是用的大模型的配置文件训练的，导致显存不够用。
> 
> 一直卡在restore model的原因多半是制作的tfrecord是空的，读不出数据，建议查看一下tfrecord的大小是不是0.

谢谢大佬的回复！感谢！那么我应该怎么设置呢？但我手边只有一块2080，显存只有11000M，我应该用小模型的配置文件吗？那么又在哪里呢。如何使其可在单块GPU上稳定训练呀？麻烦指教 多谢了 我训练简单的Rotation Retina中的python multi_gpu_train.py好像不会出错，python_multi_gpu_train_r3det.py就会报这个错误。

**Comment by yangxue0827** [comment]
建议挪步使用yangxue0827/RotationDetection，里面包含了r3det，用法和这个一致，而且给了r3det的baseline配置文件。

**Comment by yangxue0827** [comment]
https://github.com/yangxue0827/RotationDetection/blob/main/libs/configs/DOTA/r3det/cfgs_res50_dota_r3det_v1.py
gpu设置参数GPU_GROUP = '0,1,2'

**Comment by yzk-lab** [comment]
> 建议挪步使用yangxue0827/RotationDetection，里面包含了r3det，用法和这个一致，而且给了r3det的baseline配置文件。

谢谢！我去试一试这个，在配置文件中只使用一块GPU看看能不能跑起来。感谢回复！

**Comment by yzk-lab** [comment]
你好，我还有最后一个问题，就是这个pretrained_weights我下下来是ckpt文件，怎么转成一个文件夹中包含.index，.meta .checkpoint之类格式的呢？我想尝试将res101换成res50试试。
