### ISSUE TITLE
trained_weights

### ISSUE THREAD

**Issue by yzk-lab** [Thinklab-SJTU/R3Det_Tensorflow#127]
你好，我想知道我明明已经训练起来了，在trained_weights里却没有模型保存是什么原因呢？我的预训练模型如下
![image](https://user-images.githubusercontent.com/41197028/112965211-a169c300-917b-11eb-815b-80d931e72112.png)

还有你的rotation detection中pretrained weights 的有一个resnet50.npy文件是什么含义呢？我似乎没有在相关链接里找到。

**Comment by yangxue0827** [comment]
https://github.com/Thinklab-SJTU/R3Det_Tensorflow/tree/master/data/pretrained_weights

预训练权重放这

**Comment by yzk-lab** [comment]
不好意思，是不是要将trained_weights要先根据你的链接下载下来之后在进行我的训练过程呢？我看output里的readme里是这么说，我已经将pretrained_weights放到你说的目录下，但是还是没有trained_weights保存下来呀，不好意思，打扰到你。

**Comment by yangxue0827** [comment]
训练不是实时存的，要训练一段时间存一次

**Comment by yzk-lab** [comment]
是在trained_weigths里先下一个你提供的模型之后  我自己的模型才会在你的模型基础上生成吗？如果我不下载你的模型  我训练了20000多步都没有模型生成。trained_weigths始终是空的。

**Comment by yangxue0827** [comment]
你是训练得到话trained_weigths里的不用下载我提供的，我提供的是已经训练好的，供人测试的。你等着就行，会保存的

**Comment by yangxue0827** [comment]
具体多少步存一次，你看cfgs里面的参数
