### ISSUE TITLE
Can you show me cfgs_res152_dota_r3det_plusplus_v1.py?

### ISSUE THREAD

**Issue by Genie-Kim** [Thinklab-SJTU/R3Det_Tensorflow#13]
Can you show me cfgs_res152_dota_r3det_plusplus_v1.py?
If it is not possible, I would like to know which part should be changed in cfgs_res152_dota_r3det_v3.py which is currently uploaded.

**Comment by yangxue0827** [comment]
Will be released in April @Genie-Kim
