### ISSUE TITLE
test_dota_r3det_ms.py 没检测结果

### ISSUE THREAD

**Issue by homxxx** [Thinklab-SJTU/R3Det_Tensorflow#132]
解压了权重到根目录中，但是在代码没发现载入权重路径的地方，运行test也可以运行但是出来的可视化结果是原图，没有检测结果，请问如何才能运行推理部分

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/122559695-40fb6b00-d072-11eb-982e-1c3edcd66888.png)
参考权重摆放的位置，已经将对应的配置文件复制到cfgs.py中。

**Comment by homxxx** [comment]
感谢大佬！放置路径后，出来的结果like this，不知道是否正确。请问该如何得到您主页的demo图片效果和计算map值，数据集已经按照readme切分好了







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月18日(星期五) 晚上8:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Thinklab-SJTU/R3Det_Tensorflow] test_dota_r3det_ms.py 没检测结果 (#132)





 

 参考权重摆放的位置，已经将对应的配置文件复制到cfgs.py中。

**Comment by yangxue0827** [comment]
cd $PATH_ROOT/tools
python test_dota_r3det_ms.py --test_dir='/PATH/TO/IMAGES/'  
                             --gpus=0,1,2,3,4,5,6,7  
                             -ms (multi-scale testing, optional)
                             -s (visualization, optional)

请仔细看readme，测试集不需要裁剪

**Comment by homxxx** [comment]
测试集没有切分，但是运行test可视化的时候图片的预测框非常多，特别是边缘，感觉是置信度=0.01的预测结果。运行tools/inference.py则会报错 Shape must be rank 0 but is rank 1 for 'cond/cond/Switch'(op:'Switch') with input shapes : [6], [6].  请问我该如何运行才能得到置信度0.5的可视化demo？

**Comment by yangxue0827** [comment]
cd $PATH_ROOT/tools
python test_dota_r3det_ms.py --test_dir='/PATH/TO/IMAGES/'
--gpus=0,1,2,3,4,5,6,7
-ms (multi-scale testing, optional)
-s (visualization, optional)


可视化的就加上 -s

**Comment by homxxx** [comment]
用的是ResNet152_v1d 600->MS (+Flip)这个权重，cfg文件也默认是这个我看，但是运行出的图在其他issue也提到了 很多误检特别是边缘，您说用其他权重和版本，我试了下

R3Det* | ResNet101_v1d 600-&gt;800

权重也放在对应位置了，cfg也按照对应的文件去覆盖了原cfg文件的内容，运行python test_dota_r3det_ms.py时权重则会指向检测预训练权重的位置，我把权重重命名移到预训练权重后可以运行，但是出来的结果图没有预测结果

**Comment by yangxue0827** [comment]
权重则会指向检测预训练权重的位置说明你权重没放对位置或者cfgs没有找到对应的。实在不行你训练一下，存一两个权重就大概知道什么逻辑了。

推荐使用yangxue0827/RotationDetection，用法是一样的，提供了很多方法和相应的权重。

**Comment by homxxx** [comment]
你好 找到问题了，您提供的R3Det_Tensorflow/libs/configs/DOTA1.0/r3det/cfgs_res101_dota_r3det_v19.py 里面41行VERSION = 'RetinaNet_DOTA_R3Det_2x_20200628' 应该改成您网盘里面对应的名字，也就是：VERSION = 'RetinaNet_DOTA_R3Det_3x_20200628'

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/122708783-8e085880-d28f-11eb-8094-b36d56997915.png)
readme表格后面都有对应的cfgs

**Comment by homxxx** [comment]
是的，已经替换过了
![image](https://user-images.githubusercontent.com/59168249/122709030-066f1980-d290-11eb-986b-d4e0c2828a5e.png)
![image](https://user-images.githubusercontent.com/59168249/122709044-0ec75480-d290-11eb-88d1-578930492640.png)
![image](https://user-images.githubusercontent.com/59168249/122709067-18e95300-d290-11eb-9527-8130771f37c1.png)
但是对应的文件里面版本名字没对上哈

**Comment by yangxue0827** [comment]
确实有问题，我已经更新了，感谢提醒。
