### ISSUE TITLE
window训练代码和linux训练代码为什么不同？

### ISSUE THREAD

**Issue by jiangfeizi** [Thinklab-SJTU/R3Det_Tensorflow#133]
我发现window下训练代码和linux训练代码不同，请问为什么需要这样的区别，我能把linux训练方式移植到window下，会遇到什么困难？Thank you.

**Comment by jiangfeizi** [comment]
已经根据博主的其他问题回答解决，成功在windows编译。

**Comment by daili650** [comment]
> 已经根据博主的其他问题回答解决，成功在windows编译。

请问其他问题的回答是哪个，可以指路一下吗

**Comment by jiangfeizi** [comment]
https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/issues/50

不能直接用，得稍微修改一下。

**Comment by daili650** [comment]
你是直接用multi_gpu_train_win.py运行，还是修改setup.py文件？我用第一种方法提示错误：
Traceback (most recent call last):
  File "multi_gpu_train_win.py", line 365, in <module>
    train()
  File "multi_gpu_train_win.py", line 213, in train
    gpu_id=i)
  File "..\libs\networks\build_whole_network_win.py", line 240, in build_whole_detection_network
    if cfgs.REG_LOSS_MODE == 0:
AttributeError: module 'libs.configs.cfgs' has no attribute 'REG_LOSS_MODE'

**Comment by jiangfeizi** [comment]
修改还是修改setup.py文件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Thinklab-SJTU/R3Det_Tensorflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月24日(星期五) 下午3:23
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Thinklab-SJTU/R3Det_Tensorflow] window训练代码和linux训练代码为什么不同？ (#133)





 
你是直接用multi_gpu_train_win.py运行，还是修改setup.py文件？我用第一种方法提示错误：
 Traceback (most recent call last):
 File "multi_gpu_train_win.py", line 365, in 
 train()
 File "multi_gpu_train_win.py", line 213, in train
 gpu_id=i)
 File "..\libs\networks\build_whole_network_win.py", line 240, in build_whole_detection_network
 if cfgs.REG_LOSS_MODE == 0:
 AttributeError: module 'libs.configs.cfgs' has no attribute 'REG_LOSS_MODE'

**Comment by daili650** [comment]
> 修改还是修改setup.py文件
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Thinklab-SJTU/R3Det_Tensorflow" ***@***.***&gt;; 发送时间:&nbsp;2021年9月24日(星期五) 下午3:23 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [Thinklab-SJTU/R3Det_Tensorflow] window训练代码和linux训练代码为什么不同？ (#133) 你是直接用multi_gpu_train_win.py运行，还是修改setup.py文件？我用第一种方法提示错误： Traceback (most recent call last): File "multi_gpu_train_win.py", line 365, in train() File "multi_gpu_train_win.py", line 213, in train gpu_id=i) File "..\libs\networks\build_whole_network_win.py", line 240, in build_whole_detection_network if cfgs.REG_LOSS_MODE == 0: AttributeError: module 'libs.configs.cfgs' has no attribute 'REG_LOSS_MODE' — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

修改setup.py，也出现了链接中的问题：
d:\anaconda\envs\r3det_tf\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
bbox.c(1684): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
bbox.c(1693): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
bbox.c(2374): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
bbox.c(2383): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
bbox.c(3056): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
bbox.c(3065): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
bbox.c(3692): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
bbox.c(3701): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
bbox.c(4536): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
bbox.c(4545): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
bbox.c(9439): error C2039: “exc_type”: 不是“_ts”的成员
d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
bbox.c(9440): error C2039: “exc_value”: 不是“_ts”的成员
d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
bbox.c(9441): error C2039: “exc_traceback”: 不是“_ts”的成员
d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
bbox.c(9448): error C2039: “exc_type”: 不是“_ts”的成员
d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
bbox.c(9449): error C2039: “exc_value”: 不是“_ts”的成员
d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
bbox.c(9450): error C2039: “exc_traceback”: 不是“_ts”的成员
d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
bbox.c(9451): error C2039: “exc_type”: 不是“_ts”的成员
d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
bbox.c(9452): error C2039: “exc_value”: 不是“_ts”的成员
d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
bbox.c(9453): error C2039: “exc_traceback”: 不是“_ts”的成员
d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
bbox.c(9508): error C2039: “exc_type”: 不是“_ts”的成员
d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
bbox.c(9509): error C2039: “exc_value”: 不是“_ts”的成员
d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
bbox.c(9510): error C2039: “exc_traceback”: 不是“_ts”的成员
d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
bbox.c(9511): error C2039: “exc_type”: 不是“_ts”的成员
d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
bbox.c(9512): error C2039: “exc_value”: 不是“_ts”的成员
d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
bbox.c(9513): error C2039: “exc_traceback”: 不是“_ts”的成员
d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
bbox.c(9893): warning C4244: “初始化”: 从“double”转换到“float”，可能丢失数据
bbox.c(9899): warning C4244: “初始化”: 从“double”转换到“float”，可能丢失数据
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by jiangfeizi** [comment]
忘了我怎么改了，工程给你，你自己去研究


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Thinklab-SJTU/R3Det_Tensorflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月24日(星期五) 下午3:57
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Thinklab-SJTU/R3Det_Tensorflow] window训练代码和linux训练代码为什么不同？ (#133)





  
修改还是修改setup.py文件
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Thinklab-SJTU/R3Det_Tensorflow" @.&gt;; 发送时间:&nbsp;2021年9月24日(星期五) 下午3:23 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [Thinklab-SJTU/R3Det_Tensorflow] window训练代码和linux训练代码为什么不同？ (#133) 你是直接用multi_gpu_train_win.py运行，还是修改setup.py文件？我用第一种方法提示错误： Traceback (most recent call last): File "multi_gpu_train_win.py", line 365, in train() File "multi_gpu_train_win.py", line 213, in train gpu_id=i) File "..\libs\networks\build_whole_network_win.py", line 240, in build_whole_detection_network if cfgs.REG_LOSS_MODE == 0: AttributeError: module 'libs.configs.cfgs' has no attribute 'REG_LOSS_MODE' — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
  
修改setup.py，也出现了链接中的问题：
 d:\anaconda\envs\r3det_tf\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
 bbox.c(1684): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
 bbox.c(1693): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
 bbox.c(2374): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
 bbox.c(2383): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
 bbox.c(3056): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
 bbox.c(3065): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
 bbox.c(3692): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
 bbox.c(3701): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
 bbox.c(4536): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
 bbox.c(4545): warning C4244: “=”: 从“npy_intp”转换到“unsigned int”，可能丢失数据
 bbox.c(9439): error C2039: “exc_type”: 不是“_ts”的成员
 d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
 bbox.c(9440): error C2039: “exc_value”: 不是“_ts”的成员
 d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
 bbox.c(9441): error C2039: “exc_traceback”: 不是“_ts”的成员
 d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
 bbox.c(9448): error C2039: “exc_type”: 不是“_ts”的成员
 d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
 bbox.c(9449): error C2039: “exc_value”: 不是“_ts”的成员
 d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
 bbox.c(9450): error C2039: “exc_traceback”: 不是“_ts”的成员
 d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
 bbox.c(9451): error C2039: “exc_type”: 不是“_ts”的成员
 d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
 bbox.c(9452): error C2039: “exc_value”: 不是“_ts”的成员
 d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
 bbox.c(9453): error C2039: “exc_traceback”: 不是“_ts”的成员
 d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
 bbox.c(9508): error C2039: “exc_type”: 不是“_ts”的成员
 d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
 bbox.c(9509): error C2039: “exc_value”: 不是“_ts”的成员
 d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
 bbox.c(9510): error C2039: “exc_traceback”: 不是“_ts”的成员
 d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
 bbox.c(9511): error C2039: “exc_type”: 不是“_ts”的成员
 d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
 bbox.c(9512): error C2039: “exc_value”: 不是“_ts”的成员
 d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
 bbox.c(9513): error C2039: “exc_traceback”: 不是“_ts”的成员
 d:\anaconda\envs\r3det_tf\include\pystate.h(212): note: 参见“_ts”的声明
 bbox.c(9893): warning C4244: “初始化”: 从“double”转换到“float”，可能丢失数据
 bbox.c(9899): warning C4244: “初始化”: 从“double”转换到“float”，可能丢失数据
 error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe' failed with exit status 2
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

R3Det_Tensorflow.rar (112.64M, 2021年10月24日 15:58 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=2c396233219ccdc99a8d087047330a1e015f5104540b5e50485d570a071e0c575c0c4f0b51065e1c040b535259020052530b015661273863567d07473e675d5f165610550d5c4f1f175810335c&code=e9b3a381

**Comment by jiangfeizi** [comment]
python=3.6.5  tf=1.15
