### ISSUE TITLE
模型尺寸

### ISSUE THREAD

**Issue by zhouzhubin** [Thinklab-SJTU/R3Det_Tensorflow#14]
@yangxue0827 大佬，你好。我用的是自己的数据集，如果我想训练400*400的模型，直接修改IMG_SHORT_SIDE_LEN这个参数为400的话，训练1600步后，就会报RuntimeWarning: divide by zero encountered in log
  targets_dw = np.log(gt_rois[:, 2] / ex_rois[:, 2])，然后loss就直接会变成nan了，训练过800的，是可以的，但是400的不行

**Comment by yangxue0827** [comment]
你学习率调低一点试试 @zhouzhubin

**Comment by zhouzhubin** [comment]
刚降到5e-6还是会报那个错

**Comment by zhouzhubin** [comment]
@yangxue0827 
![2020-03-19 19-06-59 的屏幕截图](https://user-images.githubusercontent.com/38452175/77061255-e90c2980-6a14-11ea-88d4-433d1cba7e12.png)

**Comment by yangxue0827** [comment]
试一下过滤极小的目标，有可能你缩小图片后，目标的坐标长宽出现太小的值了 @zhouzhubin

**Comment by zhouzhubin** [comment]
@yangxue0827 恩恩，好的，谢谢啊！我过会去试试。

**Comment by lw230** [comment]
请问你解决了吗，我也遇到了跟你一样的问题，弄了好久了还是出错

**Comment by zhouzhubin** [comment]
在back_forward_convert这个函数里，我对w，h做了处理。然后就可以训练了。
![2020-04-29 15-52-21 的屏幕截图](https://user-images.githubusercontent.com/38452175/80572813-79d11e80-8a31-11ea-95ed-d33c92c2bc66.png)

**Comment by lw230** [comment]
你好，只在这个地方找到了back_forward_convert，您说的是哪个地方呀



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhouzhubin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月29日(星期三) 下午3:53
收件人:&nbsp;"Thinklab-SJTU/R3Det_Tensorflow"<R3Det_Tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"修行"<1714312353@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Thinklab-SJTU/R3Det_Tensorflow] 模型尺寸 (#14)





 
在back_forward_convert这个函数里，我对w，h做了处理。然后就可以训练了。

**Comment by lw230** [comment]
你好，只在这个地方找到了back_forward_convert，您说的是哪个地方呀
![图片](https://user-images.githubusercontent.com/56812850/80577684-df290d80-8a39-11ea-91e5-9780d02771d5.png)

**Comment by zhouzhubin** [comment]
哦哦，不好意思，我重写了一个函数，应该是backward_convert的函数，在libs/boxs_utils/coordinate_convert.py里。
![2020-04-29 17-42-21 的屏幕截图](https://user-images.githubusercontent.com/38452175/80582475-5ca44c00-8a41-11ea-961c-c52551d1b54b.png)
