### ISSUE TITLE
关于复现的问题

### ISSUE THREAD

**Issue by Taotaoxu** [Thinklab-SJTU/R3Det_Tensorflow#143]
师兄好， 

我看到你论文"SCRDet++"中提到，**TABLE 9**中的**RetinaNet-Res50**作为Baseline，其mAP为68.05%，比原DIOR论文中报告的指标65.7%高。

但不知为何我复现的RetinaNet-Res50结果是61.3%，我采用方案是，基于mmdetection默认设置，训练集为train set，没用val set参与训练，测试就在test set上测试。但我加上val set参与训练后，mAP直接提升至72.48，又比你的Baseline高很多，就很疑惑？？？

您的论文中没有提及
**你对DIOR的train-val-test set的使用情况，训练过程中有没有使用val set ?**，
而这个代码里面也没有体现，所以想问一下具体使用细节？

----------------------------------------------------------------------------------------------------------------

我在DIOR复现结果如下：

code：[mmdetection](https://github.com/open-mmlab/mmdetection)
model: RetinaNet-Res50
batch_size: 8
GPU: V100 * 1
epoch: 24
input_size: 800
hyper-parameters: [retinanet_r50_fpn_2x_coco.py](https://github.com/open-mmlab/mmdetection/blob/master/configs/retinanet/retinanet_r50_fpn_2x_coco.py)

|  author  |  model   | train  | mAP |
|  ----  |  ----  | ----  |  ----  |
|  me   | RetinaNet-Res50  | train | 61.3 |
|  me   | RetinaNet-Res50  | train+val | 72.48 |
| DIOR Paper | RetinaNet-Res50 | **train+val ?**  | 65.7 ​|
| SCRDet++  | RetinaNet-Res50 | **train+val ?**  | 68.05 ​|
|  me   | RetinaNet-Res101 | train | 62.8 |
|  me   | RetinaNet-Res101 | train+val | 73.4 |
| DIOR Paper | RetinaNet-Res101 | **train+val ?**  | 66.1 |

这个结果差异还是挺大的，像 RetinaNet-Res50@train+val=72.48，已经超过TABLE 9中SCRDet++ (RetinaNet∗-based) 的结果69.36
%了？

**Comment by yangxue0827** [comment]
我用了val集的，代码迭代过，性能比之前要好很多。

**Comment by Taotaoxu** [comment]
> 

好的，谢谢

**Comment by yangxue0827** [comment]
你的复现的结果是用我的代码跑的还是用mmdetection框架。
我用了val集的，代码迭代过，性能比之前要好很多。

**Comment by Taotaoxu** [comment]
> 你的复现的结果是用我的代码跑的还是用mmdetection框架

直接用的mmdetection

**Comment by yangxue0827** [comment]
那也能理解，mmdetection的性能会比我的代码要好的。

**Comment by Taotaoxu** [comment]
> 那也能理解，mmdetection的性能会比我的代码要好的。

你的代码也很好，只是我tensorflow不是太熟，不会写代码  ：(

**Comment by yangxue0827** [comment]
哈哈，tf受众确实少，我也已经转pytorch了
