### ISSUE TITLE
Anchor

### ISSUE THREAD

**Issue by hzhiyuan** [Thinklab-SJTU/R3Det_Tensorflow#15]
大佬好，我对Anchor的设置有些疑问。
对于H+R这一情况，在相关配置文件中只看到METHOD = 'H'这一项，在训练时好像也只用了矩形候选框，请问旋转候选框部分是在哪里实现的。

**Comment by yangxue0827** [comment]
H+R不是说两种形式的anchor，R3Det论文里有讨论，H的anchor召回率高，数量少，速度快，但是质量低，R的anchor质量高，但是数量多，速度慢。为了利用上面两种形式的优点，结合R3Det多个精修阶段的优势，第一阶段保召回重速度使用H形式的anchor，然后通过FRM过滤第一阶段回归出来的旋转框来作为后面阶段的候选框（R）。 @hzhiyuan

**Comment by hzhiyuan** [comment]
理解了！非常感谢！
