### ISSUE TITLE
Missing file ?

### ISSUE THREAD

**Issue by lamhoangtung** [Thinklab-SJTU/R3Det_Tensorflow#2]
I don't find `multi_gpu_train_r3det.py`, `test_dota_r3det.py` file. Can you update them ? Thanks !

**Comment by lamhoangtung** [comment]
@yangxue0827 Hi, can you update the code so we can test the pertained model. Thanks !

**Comment by zuanqianyanzi** [comment]
Was there anyone download this code?

**Comment by ibrahimsoliman97** [comment]
The author never upload any code in this repository.

**Comment by yangxue0827** [comment]
Will open source in February @lamhoangtung @zuanqianyanzi @ibrahimsoliman97

**Comment by yangxue0827** [comment]
The code is released.

**Comment by lamhoangtung** [comment]
Thanks you @yangxue0827
