### ISSUE TITLE
train occur NAN

### ISSUE THREAD

**Issue by adamzhu1990** [Thinklab-SJTU/R3Det_Tensorflow#20]
bbox_transform.py:98: RuntimeWarning: divide by zero encountered in log
  targets_dw = np.log(gt_rois[:, 2] / ex_rois[:, 2])
************************************************************
2020-04-07 20:04:45: global_step:140  current_step:140
per_cost_time:0.687s
cls_loss:1.132
reg_loss:nan
refine_cls_loss:0.161
refine_reg_loss:0.000
refine_cls_loss_stage3:0.161
refine_reg_loss_stage3:0.000
total_losses:nan

I use the DOAT1.5, is that means the dataset labels rbbox transform crossing the boundary? how can I solve it?

**Comment by yangxue0827** [comment]
https://github.com/Thinklab-SJTU/R3Det_Tensorflow/issues/4

**Comment by adamzhu1990** [comment]
now, I try it on the DOTA1.0 all the same😂

**Comment by yangxue0827** [comment]
Do you use the configuration file I provided？ @adamzhu1990

**Comment by adamzhu1990** [comment]
yes, I use the cfgs_res50_dota_r3det_v2.py as default configuration file

**Comment by zsh1234567** [comment]
First of all, thanks to the author for the code.
I have used the parameters given by the author, the results I got are as follows.
However,"I find the refine_reg_loss_stage3:0.00",Its value is 0, is this normal?

2020-04-19 20:51:29: global_step:2560  current_step:2560
per_cost_time:1.864s
cls_loss:0.979
reg_loss:1.603
refine_cls_loss:1.234
refine_reg_loss:1.127
refine_cls_loss_stage3:0.001
refine_reg_loss_stage3:0.000
total_losses:4.946

**Comment by lw230** [comment]
I have the same problem as you.Have you solved it?

**Comment by Lo1n** [comment]
same question

**Comment by yangxue0827** [comment]
The reason for this (NAN after 'bbox_transform.py:98: RuntimeWarning: divide by zero encountered in log') is that the model predicts a very small box (w and h are close to 0), which leads to a problem with the encoding and decoding of the bounding box. I will upload the repaired code and it is still being debugged. @adamzhu1990 @zsh1234567 @
