### ISSUE TITLE
data_crop之后效果很好，但是原图的效果就很差？

### ISSUE THREAD

**Issue by tcxia** [Thinklab-SJTU/R3Det_Tensorflow#21]

**Comment by yangxue0827** [comment]
请描述清楚问题，什么是原图效果很差？ @tcxia

**Comment by tcxia** [comment]
@yangxue0827 原图大小1920*1080，在原图上标注小物体，送入网络训练，做Infer的时候效果较差。将原图中目标区域截取出来，变成800*800，送入网络训练，做infer的效果就不错

**Comment by yangxue0827** [comment]
训练和测试是图片的大小要保持一致，这样效果才好。

**Comment by zsh1234567** [comment]
你好，你跑通代码了吗？我是一个初学者，有一些疑问，请问一下，你能给我了联系方式，向您请教以下吗？

**Comment by tcxia** [comment]
@zsh1234567 嗯嗯，跑通了，后面做了一些bbox映射就可以了
