### ISSUE TITLE
复现不出70.16

### ISSUE THREAD

**Issue by hzhiyuan** [Thinklab-SJTU/R3Det_Tensorflow#24]
大佬你好，我尝试复现出R3Det+数据扩充的结果（70.16）。在原cfgs.py中修改四个数据扩充项为True。结果只有66点几。请问一下大佬训练时有没有什么策略？谢谢！

**Comment by lw230** [comment]
请问您指的数据扩充项是什么意思，我搭建了r3det网络，但精度只有42，请问您是怎么提高精度的？急求！

**Comment by yangxue0827** [comment]
我的意思是数据增强。首先你是自己重写了代码，还是说用我的代码没跑出相应的结果，我给的r3det-res50不加任何数据增强就可以在DOTA数据集上到65+的。 @lw230

**Comment by lw230** [comment]
是用GitHub上的代码直接复现的，用的是DOTA1.5的数据，配置文件是cfgs.py，r3det-resnet152

**Comment by yangxue0827** [comment]
参考这个https://github.com/Thinklab-SJTU/R3Det_Tensorflow/issues/4 @lw230

**Comment by lw230** [comment]
> 大佬你好，我尝试复现出R3Det+数据扩充的结果（70.16）。在原cfgs.py中修改四个数据扩充项为True。结果只有66点几。请问一下大佬训练时有没有什么策略？谢谢！

请问是哪几个数据扩充项，不是很懂哪些是

**Comment by lw230** [comment]
我也是遇到了这样的情况，不增反减，请问您解决了吗

**Comment by zsh1234567** [comment]
> 请问您指的数据扩充项是什么意思，我搭建了r3det网络，但精度只有42，请问您是怎么提高精度的？急求！

你好，精度只有42，是不是某些类别结果很差。请问你的问题解决了么
