### ISSUE TITLE
HRSC2016数据集的预训练模型

### ISSUE THREAD

**Issue by RicardoY97** [Thinklab-SJTU/R3Det_Tensorflow#27]
我看到configs中有关于HRSC2016数据集的相关设置，但是我没有找到R3Det关于HRSC2016数据集的预训练模型，请问在哪里可以获得它？

**Comment by yangxue0827** [comment]
预训练权重是部分数据集的。你应该指的是训练好的权重吧，这个我没有上传，需要你自己重新训练一下。 @RicardoY97

**Comment by lw230** [comment]
作者您好，我想单纯的复现您用HRSC2016数据集训练和评估得到的结果：map=89%。我从http://ddl.escience.cn下载了HRSC2016数据集，按照train.txt文档挑选了436张图作为训练的数据集，并且用您在这里给出的data/io/HRSC2016/make_test_xml.py文件将annotation转换成了相应的四点坐标，用cfgs_res152_hrsc2016_r3det_v2.py作为配置文件，运行了multi_gpu-train_r3det.py进行训练，但是训练过程中损失非常大，几百上千都有，请问要怎样才能复现您的结果？您是怎么做的？

**Comment by lw230** [comment]
作者您好，我想单纯的复现您用HRSC2016数据集训练和评估得到的结果：map=89%。我从http://ddl.escience.cn下载了HRSC2016数据集，按照train.txt文档挑选了436张图作为训练的数据集，并且用您在这里给出的data/io/HRSC2016/make_test_xml.py文件将annotation转换成了相应的四点坐标，用cfgs_res152_hrsc2016_r3det_v2.py作为配置文件，运行了multi_gpu-train_r3det.py进行训练，但是训练过程中损失非常大，几百上千都有，请问要怎样才能复现您的结果？您是怎么做的？
