### ISSUE TITLE
用HRSC2016数据集训练

### ISSUE THREAD

**Issue by lw230** [Thinklab-SJTU/R3Det_Tensorflow#29]
作者您好，请问你用HRSC数据集做实验的训练集有多少张图片，是论文里提到的436张吗，

**Comment by lw230** [comment]
作者您好，我想单纯的复现您用HRSC2016数据集训练和评估得到的结果：map=89%。我从http://ddl.escience.cn/下载了HRSC2016数据集，按照train.txt文档挑选了436张图作为训练的数据集，并且用您在这里给出的data/io/HRSC2016/make_test_xml.py文件将annotation转换成了相应的四点坐标，用cfgs_res152_hrsc2016_r3det_v2.py作为配置文件，运行了multi_gpu-train_r3det.py进行训练，但是训练过程中损失非常大，几百上千都有，请问要怎样才能复现您的结果？您是怎么做的？

**Comment by lw230** [comment]
作者您好，我想单纯的复现您用HRSC2016数据集训练和评估得到的结果：map=89%。我从http://ddl.escience.cn/下载了HRSC2016数据集，按照train.txt文档挑选了436张图作为训练的数据集，并且用您在这里给出的data/io/HRSC2016/make_test_xml.py文件将annotation转换成了相应的四点坐标，用cfgs_res152_hrsc2016_r3det_v2.py作为配置文件，运行了multi_gpu-train_r3det.py进行训练，但是训练过程中损失非常大，几百上千都有，请问要怎样才能复现您的结果？您是怎么做的？

**Comment by JuiceTao** [comment]
您好，请问您最后复现结果了吗？可以请较一下训练细节吗？
