### ISSUE TITLE
多GPU运行会出现截图中的错误

### ISSUE THREAD

**Issue by dgy20122016** [Thinklab-SJTU/R3Det_Tensorflow#30]
执行python multi_gpu_train_r3det.py，多GPU运行会出现截图中的错误，切换成一个GPU就不会出现，错误如下：
InternalError (see above for traceback): WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true / nonzero indices.  temp_storage_bytes: 5887, status: invalid resource handle
         [[node tower_1/build_refine_loss/Where_2 (defined at ../libs/losses/losses.py:56)  = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:GPU:0"](tower_1/build_refine_loss/Equal)]]

请问如何解决这个问题。

**Comment by yangxue0827** [comment]
显存多大？另外降低tf版本试试。
