### ISSUE TITLE
inference没有输出框

### ISSUE THREAD

**Issue by Wo-Ki** [Thinklab-SJTU/R3Det_Tensorflow#34]
你好，在自己的数据集上训练resnet50_v1d，在测试集上测试，没有框。我输出：
`show_indices = detected_scores >= cfgs.VIS_SCORE
 print(show_indices)`
结果也是空。在训练的tensorboard里显示图片似乎有损坏，但下载下来图片完好。请问是什么问题？
![image](https://user-images.githubusercontent.com/29698317/84844349-bb1e9b80-b07c-11ea-96ca-af5cc737f21a.png)

**Comment by yangxue0827** [comment]
可能是你图片的w和h写反了

**Comment by Wo-Ki** [comment]
> 可能是你图片的w和h写反了

查到问题了，是输出图片必须800x800？

**Comment by yangxue0827** [comment]
不是必须的

**Comment by Wo-Ki** [comment]
> 不是必须的

我把图片都缩放到800x800，tensorbord log就没有问题了。之前损失都不降，现在应该可以了

**Comment by yangxue0827** [comment]
你要检查你的xml是不是w和h写反了，导致reshape图片错了

**Comment by Wo-Ki** [comment]
> 你要检查你的xml是不是w和h写反了，导致reshape图片错了

好的，谢谢
