### ISSUE TITLE
Cannot compile C code in box_utils

### ISSUE THREAD

**Issue by zouxiaoshi** [Thinklab-SJTU/R3Det_Tensorflow#35]
Errors:
bbox.c: In function ‘__Pyx__ExceptionSave’:
bbox.c:9439:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     *type = tstate->exc_type;

Actually i have solved this problem by deleting .c files in box_utils.
Just a reminder for those have same the problems can have an access to solve it.

Analysis:
The incompatibility of Cython and .c files will raise the  above error.
After you updated the Cython, you would find it useless for that those old .c files will not be covered by the new generated .c files.
Delete  the old .c files, and then recompile it, you will find anything goes well.

**Comment by Kongsea** [comment]
In the folder `$PATH_ROOT/libs/box_utils/cython_utils`, the error disappeared after deleting c files. However, in the folder `$PATH_ROOT/libs/box_utils/`, when run `python setup.py build_ext --inplace`, the same error was still raised.
Could you please give some advice? Thank you.

**Comment by yangxue0827** [comment]
Use my docker？

**Comment by Kongsea** [comment]
Clone your code... @yangxue0827

**Comment by yangxue0827** [comment]
I mean you can use my docker image if the problem is caused by the development environment.

**Comment by Kongsea** [comment]
I create a new anaconda environment using python 2.x and the error disappeared...

**Comment by Kongsea** [comment]
```
cd $PATH_ROOT/libs/box_utils/cython_utils
rm *.so
python setup.py build_ext --inplace (or make)

cd $PATH_ROOT/libs/box_utils/
rm *.so
rm *.cpp
python setup.py build_ext --inplace
```
