### ISSUE TITLE
about RetinaNet cfgs's question

### ISSUE THREAD

**Issue by PC-god** [Thinklab-SJTU/R3Det_Tensorflow#36]
RetinaNet | ResNet50_v1d 600->800 | DOTA1.0 trainval | DOTA1.0 test | 68.65 | 1X GeForce RTX 2080 Ti | 1 | R | iou-smooth L1 | 1x | No | cfgs_res50_dota_v5.py
in your model zoo，i only want to use 7th version, then its cfg may not match.
there is not  in 'REFINE_IOU_POSITIVE_THRESHOLD',  'REFINE_IOU_NEGATIVE_THRESHOLD', 'USE_IOU_FACTOR'.
I don't know 'lr schd- 1x' meaning. 
My application is simple that is two classes.
(汉语回答也行)

**Comment by yangxue0827** [comment]
一个epoch包含一遍（1x）完整的数据集

**Comment by PC-god** [comment]
refine_retinanet相比retina-net，修改了哪里（大概说就行）
build_refine_loss里，对refine net里的refine_boxes算label时， 区分正负例的iou，还记得么，
谢谢啦

**Comment by yangxue0827** [comment]
refine retinatnet就是多个阶段的retinanet，类似refindet操作，具体的阈值你看r3det论文就行，他和r3det的区别就是没有FRM模块，是r3det的baseline。都在r3det论文里有描述。

**Comment by PC-god** [comment]
好的，谢谢
