### ISSUE TITLE
How about set H +  R anchors?

### ISSUE THREAD

**Issue by PC-god** [Thinklab-SJTU/R3Det_Tensorflow#37]
在您的论文中，‘anchor combination strategy.  the horizontal anchors are used in the ﬁrst stage for faster speed and more proposals, and then the reﬁned rotating anchors are used in the reﬁnement stages to adapt to intensive scenarios。 ’
水平框 在第一阶段可以加速， 优化阶段用 优化过的旋转框
可是在代码中： rpn部分和后面refine stage都用R-anchor，没像论文中所说：用水平锚加速，用旋转锚提高准确率。
不知道 我看的对不对

**Comment by yangxue0827** [comment]
第一阶段用水平anchor就是指rpn这个阶段

**Comment by PC-god** [comment]
那 cfgs.METHOD == 'H' or 'R', 因此整个网络只产生了一次anchor，确定了先验的是带角度或不带角度anchor，后面无论是rpn还是 refine_stage用的 同样的先验。只不过在 refine stage阶段有过滤，且预测是rpn预测box与gt的差值。
我想问的就是：H+R怎么做到的 （权当学习） ~_~

**Comment by yangxue0827** [comment]
就是指rpn用H的anchor，回归出旋转的框（R）给后续的精修阶段。而cfgs里面的H和R只代表才用哪种形式的anchor，论文里是用H

**Comment by PC-god** [comment]
明白了，谢谢谢谢！
