### ISSUE TITLE
box_utils/cython_utils下无cython_box

### ISSUE THREAD

**Issue by ChunmianLin** [Thinklab-SJTU/R3Det_Tensorflow#39]
你好，我按readme的compile步骤，在第一部make完后，没有看到cython_utils文件夹下由cython_box生成，这导致在anchor_target_layer_without_boxweight脚本中会出现导入错误，请问这个是怎么回事？
谢谢

**Comment by PC-god** [comment]
我是在linux下用，setup.py那个文件编译会生成.so文件（rbbox_overlaps、 rotate_polygon_nms、iou_cpu）。window下我没成功。
另外你的问题，描述不清晰啊

**Comment by zouxiaoshi** [comment]
你应该是缺少 相应.so 文件 anchor_target_layer_without_boxweigh 依赖cython_bbox 的.so文件，由于.so 文件没有被正确生成所导致的。 建议是： 1. 更新cython 2.删除所有的 .c .cpp 【保留hpp】文件，然后重新 make 或 执行setup.py。

**Comment by ChunmianLin** [comment]
> 我是在linux下用，setup.py那个文件编译会生成.so文件（rbbox_overlaps、 rotate_polygon_nms、iou_cpu）。window下我没成功。
> 另外你的问题，描述不清晰啊

你好，我也是在linux下编译的。我的问题在于：编译完虽然也会生成rbbox_overlaps.so文件。但是在anchor_target_layer_without_boxweight脚本的import部分，会出现导入错误‘no module named rbbox_overlaps’，不知道这种情况该怎么办。对c/c++这种动态链接库编译不熟悉，有点不理解(我的理解是编译完会生成rbbox_overlap.py文件，然后通过import来导入)。
另外我还有个疑问就是：在这个项目的大部分文件中from ... import(比如from libs.box_utils import...) 这种导入格式，老是会报'no module named libs'，我不太明白，感觉和上面的是一个类型问题，就是找不到导入模块。网上也试图找问题解决办法，诸如一些设置__ini__.py文件等等我都检查过了，实在不懂如何解决，应该是我对c/c++不熟悉导致的。
能否具体的指点下！感谢！

**Comment by ChunmianLin** [comment]
> 你应该是缺少 相应.so 文件 anchor_target_layer_without_boxweigh 依赖cython_bbox 的.so文件，由于.so 文件没有被正确生成所导致的。 建议是： 1. 更新cython 2.删除所有的 .c .cpp 【保留hpp】文件，然后重新 make 或 执行setup.py。

谢谢。我按你说的方式，更新、删除、再make。结果好像还是跟之前一样：就是box_utils文件价中会生成一些.so文件，如cython_bbox.cpython-35m-x86_64-linux-gnu.so这样的文件，就是跟脚本中import的不一样：如anchor_target_layer_without_boxweight脚本中from ...cython_utils.cython_bbox import bbox_overlaps。
我也不明白问题出在哪里，这是说明我编译没通过的意思吗，就是没生成相应的东西？
麻烦指点下，感谢！

**Comment by zouxiaoshi** [comment]
> > 你应该是缺少 相应.so 文件 anchor_target_layer_without_boxweigh 依赖cython_bbox 的.so文件，由于.so 文件没有被正确生成所导致的。 建议是： 1. 更新cython 2.删除所有的 .c .cpp 【保留hpp】文件，然后重新 make 或 执行setup.py。
> 
> 谢谢。我按你说的方式，更新、删除、再make。结果好像还是跟之前一样：就是box_utils文件价中会生成一些.so文件，如cython_bbox.cpython-35m-x86_64-linux-gnu.so这样的文件，就是跟脚本中import的不一样：如anchor_target_layer_without_boxweight脚本中from ...cython_utils.cython_bbox import bbox_overlaps。
> 我也不明白问题出在哪里，这是说明我编译没通过的意思吗，就是没生成相应的东西？
> 麻烦指点下，感谢！

1. 如果可以的话，麻烦截个图，会更方便些。
2. bbox_overlaps 定义在 cython_utils.bbox.pyx 文件中，编译这个文件会生成cython_bbox.cpython-35m-x86_64-linux-gnu.so 和 bbox.c 文件 [详情看setup.py]，所以，如果你导入不成功的话，应该是.so 文件没有成功生成。
3. 一般意义上 import 导入不成功，有两个原因， 一： 找不到路径，你没有把相应路径添加到环境变量中    二：文件或函数不存在
4. 我这里有python3.7版本 .so 文件，如果你需要的话，我可以发给你。

**Comment by ChunmianLin** [comment]
> > > 你应该是缺少 相应.so 文件 anchor_target_layer_without_boxweigh 依赖cython_bbox 的.so文件，由于.so 文件没有被正确生成所导致的。 建议是： 1. 更新cython 2.删除所有的 .c .cpp 【保留hpp】文件，然后重新 make 或 执行setup.py。
> > 
> > 
> > 谢谢。我按你说的方式，更新、删除、再make。结果好像还是跟之前一样：就是box_utils文件价中会生成一些.so文件，如cython_bbox.cpython-35m-x86_64-linux-gnu.so这样的文件，就是跟脚本中import的不一样：如anchor_target_layer_without_boxweight脚本中from ...cython_utils.cython_bbox import bbox_overlaps。
> > 我也不明白问题出在哪里，这是说明我编译没通过的意思吗，就是没生成相应的东西？
> > 麻烦指点下，感谢！
> 
> 1. 如果可以的话，麻烦截个图，会更方便些。
> 2. bbox_overlaps 定义在 cython_utils.bbox.pyx 文件中，编译这个文件会生成cython_bbox.cpython-35m-x86_64-linux-gnu.so 和 bbox.c 文件 [详情看setup.py]，所以，如果你导入不成功的话，应该是.so 文件没有成功生成。
> 3. 一般意义上 import 导入不成功，有两个原因， 一： 找不到路径，你没有把相应路径添加到环境变量中    二：文件或函数不存在
> 4. 我这里有python3.7版本 .so 文件，如果你需要的话，我可以发给你。
感谢！我编译完的文件还有代码中的问题截图如下：就是编译完会生成so文件，但是代码中的import错误仍在存在。
![Screenshot from 2020-06-30 16-33-19](https://user-images.githubusercontent.com/53289159/86103773-c7304180-baef-11ea-84ce-1a6a7a5ed09f.png)
这样是什么问题呢？

**Comment by zouxiaoshi** [comment]
> > > 你应该是缺少 相应.so 文件 anchor_target_layer_without_boxweigh 依赖cython_bbox 的.so文件，由于.so 文件没有被正确生成所导致的。 建议是： 1. 更新cython 2.删除所有的 .c .cpp 【保留hpp】文件，然后重新 make 或 执行setup.py。
> > 
> > 
> > 谢谢。我按你说的方式，更新、删除、再make。结果好像还是跟之前一样：就是box_utils文件价中会生成一些.so文件，如cython_bbox.cpython-35m-x86_64-linux-gnu.so这样的文件，就是跟脚本中import的不一样：如anchor_target_layer_without_boxweight脚本中from ...cython_utils.cython_bbox import bbox_overlaps。
> > 我也不明白问题出在哪里，这是说明我编译没通过的意思吗，就是没生成相应的东西？
> > 麻烦指点下，感谢！
> 
> 1. 如果可以的话，麻烦截个图，会更方便些。
> 2. bbox_overlaps 定义在 cython_utils.bbox.pyx 文件中，编译这个文件会生成cython_bbox.cpython-35m-x86_64-linux-gnu.so 和 bbox.c 文件 [详情看setup.py]，所以，如果你导入不成功的话，应该是.so 文件没有成功生成。
> 3. 一般意义上 import 导入不成功，有两个原因， 一： 找不到路径，你没有把相应路径添加到环境变量中    二：文件或函数不存在
> 4. 我这里有python3.7版本 .so 文件，如果你需要的话，我可以发给你。
>    感谢！我编译完的文件还有代码中的问题截图如下：就是编译完会生成so文件，但是代码中的import错误仍在存在。
>    ![Screenshot from 2020-06-30 16-33-19](https://user-images.githubusercontent.com/53289159/86103773-c7304180-baef-11ea-84ce-1a6a7a5ed09f.png)
>    这样是什么问题呢？

1. 能够确认的是 路径是对的。
2. 从IDE上面的标记来看，应该是 找不到cython_bbox，而非cython_bbox里的bbox_overlaps。
3. 应该还是.so 文件的问题,  python 可以直接import   .so 文件，你可以cd 到cython_utils，然后 import cython_bbox 看看错误信息提示是什么，方便进一步debug
4. 个人的直觉，你可以升级python 版本到3.7试试（建议最新的cython版本），然后再重新删除之前的.so .c 文件，重新编译。

**Comment by ChunmianLin** [comment]
> > > > 你应该是缺少 相应.so 文件 anchor_target_layer_without_boxweigh 依赖cython_bbox 的.so文件，由于.so 文件没有被正确生成所导致的。 建议是： 1. 更新cython 2.删除所有的 .c .cpp 【保留hpp】文件，然后重新 make 或 执行setup.py。
> > > 
> > > 
> > > 谢谢。我按你说的方式，更新、删除、再make。结果好像还是跟之前一样：就是box_utils文件价中会生成一些.so文件，如cython_bbox.cpython-35m-x86_64-linux-gnu.so这样的文件，就是跟脚本中import的不一样：如anchor_target_layer_without_boxweight脚本中from ...cython_utils.cython_bbox import bbox_overlaps。
> > > 我也不明白问题出在哪里，这是说明我编译没通过的意思吗，就是没生成相应的东西？
> > > 麻烦指点下，感谢！
> > 
> > 
> > 
> > 1. 如果可以的话，麻烦截个图，会更方便些。
> > 2. bbox_overlaps 定义在 cython_utils.bbox.pyx 文件中，编译这个文件会生成cython_bbox.cpython-35m-x86_64-linux-gnu.so 和 bbox.c 文件 [详情看setup.py]，所以，如果你导入不成功的话，应该是.so 文件没有成功生成。
> > 3. 一般意义上 import 导入不成功，有两个原因， 一： 找不到路径，你没有把相应路径添加到环境变量中    二：文件或函数不存在
> > 4. 我这里有python3.7版本 .so 文件，如果你需要的话，我可以发给你。
> >    感谢！我编译完的文件还有代码中的问题截图如下：就是编译完会生成so文件，但是代码中的import错误仍在存在。
> >    ![Screenshot from 2020-06-30 16-33-19](https://user-images.githubusercontent.com/53289159/86103773-c7304180-baef-11ea-84ce-1a6a7a5ed09f.png)
> >    这样是什么问题呢？
> 
> 1. 能够确认的是 路径是对的。
> 2. 从IDE上面的标记来看，应该是 找不到cython_bbox，而非cython_bbox里的bbox_overlaps。
> 3. 应该还是.so 文件的问题,  python 可以直接import   .so 文件，你可以cd 到cython_utils，然后 import cython_bbox 看看错误信息提示是什么，方便进一步debug
> 4. 个人的直觉，你可以升级python 版本到3.7试试（建议最新的cython版本），然后再重新删除之前的.so .c 文件，重新编译。

感谢！我重新更新了版本，然后编译没报问题了。但是出现一个新问题，在draw_box_in_img和show_box_in_tensor部分，报错list of the index。我知道这问题的意思，但是找不出问题所在。不知你们是否碰过这个问题，请指教下：
![Screenshot from 2020-07-01 14-00-55](https://user-images.githubusercontent.com/53289159/86208526-521e4400-bba3-11ea-9011-fdde1a7af136.png)
顺便再请教大家一个问题，就是dota数据集的类别序号是从0还是1开始呢？哦感觉这里是不是跟我类别序号的设置有关系呢，导致box和lable的维度错误，我的序号是从0开始的。
欢迎大家交流，感谢！

**Comment by zouxiaoshi** [comment]
> 家交

1. 你看下 libs/box_utils/draw_box_in_img.py 里的  draw_a_rectangel_in_img  这是出错的地方（可从图中最后几行看出），这个函数里唯一有可能index error的就只有 box了，然后返回到 multi_gpu_train.py 可知，box 指的是 gtboxes_and_label_r[:, :-1] 也就是你自己做的标注框。 所以 最终推测 就是  你标注的格式不对，这里的标注框是rotated boxes 它需要四个点的信息，并不是以往的rectangle 只需要对角线上两点的信息。也或者说 你的tf_record 不对，需要检查下你的标注文件 以及 建议最好读取下 tf_record，看看输入值正确否。
2. 一般的目标检测任务都会默认 标记 background 为 0

**Comment by ChunmianLin** [comment]
> > > > 你应该是缺少 相应.so 文件 anchor_target_layer_without_boxweigh 依赖cython_bbox 的.so文件，由于.so 文件没有被正确生成所导致的。 建议是： 1. 更新cython 2.删除所有的 .c .cpp 【保留hpp】文件，然后重新 make 或 执行setup.py。
> > > 
> > > 
> > > 谢谢。我按你说的方式，更新、删除、再make。结果好像还是跟之前一样：就是box_utils文件价中会生成一些.so文件，如cython_bbox.cpython-35m-x86_64-linux-gnu.so这样的文件，就是跟脚本中import的不一样：如anchor_target_layer_without_boxweight脚本中from ...cython_utils.cython_bbox import bbox_overlaps。
> > > 我也不明白问题出在哪里，这是说明我编译没通过的意思吗，就是没生成相应的东西？
> > > 麻烦指点下，感谢！
> > 
> > 
> > 
> > 1. 如果可以的话，麻烦截个图，会更方便些。
> > 2. bbox_overlaps 定义在 cython_utils.bbox.pyx 文件中，编译这个文件会生成cython_bbox.cpython-35m-x86_64-linux-gnu.so 和 bbox.c 文件 [详情看setup.py]，所以，如果你导入不成功的话，应该是.so 文件没有成功生成。
> > 3. 一般意义上 import 导入不成功，有两个原因， 一： 找不到路径，你没有把相应路径添加到环境变量中    二：文件或函数不存在
> > 4. 我这里有python3.7版本 .so 文件，如果你需要的话，我可以发给你。
> >    感谢！我编译完的文件还有代码中的问题截图如下：就是编译完会生成so文件，但是代码中的import错误仍在存在。
> >    ![Screenshot from 2020-06-30 16-33-19](https://user-images.githubusercontent.com/53289159/86103773-c7304180-baef-11ea-84ce-1a6a7a5ed09f.png)
> >    这样是什么问题呢？
> 
> 1. 能够确认的是 路径是对的。
> 2. 从IDE上面的标记来看，应该是 找不到cython_bbox，而非cython_bbox里的bbox_overlaps。
> 3. 应该还是.so 文件的问题,  python 可以直接import   .so 文件，你可以cd 到cython_utils，然后 import cython_bbox 看看错误信息提示是什么，方便进一步debug
> 4. 个人的直觉，你可以升级python 版本到3.7试试（建议最新的cython版本），然后再重新删除之前的.so .c 文件，重新编译。

感谢！
1.我的数据格式是voc，也就是说每个xml中是xmin，ymin，xmax，ymax。我看在这项目中convert_data_to_tfr_record是用来住转换数据格式的，而且读取的也是voc xml格式。所以，如果转换错了，也应该是这代码中没有进行坐标转换把？(我正在read数据，检查下，而且我确实发现在这代码中转换函数下有给return的格式，如你所说，是四个坐标的值加上标签)
2.看来是我错了？我一直是将自己的类别设为从0开始的哦，而background我知道是要考虑，但是一般不是标记为0.在这里，
我的类别序号是从0开始的，所以我应该重新转换下数据把？而且我怀疑后面的维度错误，是不是也可能跟我这个序号有关系呢？
再次感谢大佬的指点！期待答复和进一步交流，收益很大。

**Comment by ChunmianLin** [comment]
@zouxiaoshi 请问下，项目中convert_data_to_tfrecord脚本需要进行修改吗？我看脚本中并没有进行数据坐标变换把？

**Comment by zouxiaoshi** [comment]
> @zouxiaoshi 请问下，项目中convert_data_to_tfrecord脚本需要进行修改吗？我看脚本中并没有进行数据坐标变换把？

建议单独写个脚本做转换。
作者用的是开源的数据集，这些数据集已经是4个点了（x1,y1,x2,y2,x3,y3,x4,y4）。
labemimg 得到的是 xmin,ymin,xmax,ymax，x1 = xmin,y1=ymin, x2=xmax,y2=ymin,x3=xmax,y3=ymax,x4=xmin,y4=ymax 
如果你用的是rolabelimg 做的旋转矩形，转起来稍微复杂点，参考 https://github.com/cgvict/roLabelImg/blob/316da904960259ce9e68030505797bbbe2fad531/libs/pascal_voc_io.py#L237

**Comment by zouxiaoshi** [comment]
> > > > > 你应该是缺少 相应.so 文件 anchor_target_layer_without_boxweigh 依赖cython_bbox 的.so文件，由于.so 文件没有被正确生成所导致的。 建议是： 1. 更新cython 2.删除所有的 .c .cpp 【保留hpp】文件，然后重新 make 或 执行setup.py。
> > > > 
> > > > 
> > > > 谢谢。我按你说的方式，更新、删除、再make。结果好像还是跟之前一样：就是box_utils文件价中会生成一些.so文件，如cython_bbox.cpython-35m-x86_64-linux-gnu.so这样的文件，就是跟脚本中import的不一样：如anchor_target_layer_without_boxweight脚本中from ...cython_utils.cython_bbox import bbox_overlaps。
> > > > 我也不明白问题出在哪里，这是说明我编译没通过的意思吗，就是没生成相应的东西？
> > > > 麻烦指点下，感谢！
> > > 
> > > 
> > > 
> > > 1. 如果可以的话，麻烦截个图，会更方便些。
> > > 2. bbox_overlaps 定义在 cython_utils.bbox.pyx 文件中，编译这个文件会生成cython_bbox.cpython-35m-x86_64-linux-gnu.so 和 bbox.c 文件 [详情看setup.py]，所以，如果你导入不成功的话，应该是.so 文件没有成功生成。
> > > 3. 一般意义上 import 导入不成功，有两个原因， 一： 找不到路径，你没有把相应路径添加到环境变量中    二：文件或函数不存在
> > > 4. 我这里有python3.7版本 .so 文件，如果你需要的话，我可以发给你。
> > >    感谢！我编译完的文件还有代码中的问题截图如下：就是编译完会生成so文件，但是代码中的import错误仍在存在。
> > >    ![Screenshot from 2020-06-30 16-33-19](https://user-images.githubusercontent.com/53289159/86103773-c7304180-baef-11ea-84ce-1a6a7a5ed09f.png)
> > >    这样是什么问题呢？
> > 
> > 
> > 
> > 1. 能够确认的是 路径是对的。
> > 2. 从IDE上面的标记来看，应该是 找不到cython_bbox，而非cython_bbox里的bbox_overlaps。
> > 3. 应该还是.so 文件的问题,  python 可以直接import   .so 文件，你可以cd 到cython_utils，然后 import cython_bbox 看看错误信息提示是什么，方便进一步debug
> > 4. 个人的直觉，你可以升级python 版本到3.7试试（建议最新的cython版本），然后再重新删除之前的.so .c 文件，重新编译。
> 
> 感谢！
> 1.我的数据格式是voc，也就是说每个xml中是xmin，ymin，xmax，ymax。我看在这项目中convert_data_to_tfr_record是用来住转换数据格式的，而且读取的也是voc xml格式。所以，如果转换错了，也应该是这代码中没有进行坐标转换把？(我正在read数据，检查下，而且我确实发现在这代码中转换函数下有给return的格式，如你所说，是四个坐标的值加上标签)
> 2.看来是我错了？我一直是将自己的类别设为从0开始的哦，而background我知道是要考虑，但是一般不是标记为0.在这里，
> 我的类别序号是从0开始的，所以我应该重新转换下数据把？而且我怀疑后面的维度错误，是不是也可能跟我这个序号有关系呢？
> 再次感谢大佬的指点！期待答复和进一步交流，收益很大。

不敢妄称大佬，苦逼程序员一枚，正好这些天需要做一些large rotated objects，看到这个，共同学习。
建议读下源码，了解下代码结构，方便进一步训练。
也可以了解下作者的paper以及知乎的文章，方便进一步学习。

**Comment by ChunmianLin** [comment]
> > > > > > 你应该是缺少 相应.so 文件 anchor_target_layer_without_boxweigh 依赖cython_bbox 的.so文件，由于.so 文件没有被正确生成所导致的。 建议是： 1. 更新cython 2.删除所有的 .c .cpp 【保留hpp】文件，然后重新 make 或 执行setup.py。
> > > > > 
> > > > > 
> > > > > 谢谢。我按你说的方式，更新、删除、再make。结果好像还是跟之前一样：就是box_utils文件价中会生成一些.so文件，如cython_bbox.cpython-35m-x86_64-linux-gnu.so这样的文件，就是跟脚本中import的不一样：如anchor_target_layer_without_boxweight脚本中from ...cython_utils.cython_bbox import bbox_overlaps。
> > > > > 我也不明白问题出在哪里，这是说明我编译没通过的意思吗，就是没生成相应的东西？
> > > > > 麻烦指点下，感谢！
> > > > 
> > > > 
> > > > 
> > > > 1. 如果可以的话，麻烦截个图，会更方便些。
> > > > 2. bbox_overlaps 定义在 cython_utils.bbox.pyx 文件中，编译这个文件会生成cython_bbox.cpython-35m-x86_64-linux-gnu.so 和 bbox.c 文件 [详情看setup.py]，所以，如果你导入不成功的话，应该是.so 文件没有成功生成。
> > > > 3. 一般意义上 import 导入不成功，有两个原因， 一： 找不到路径，你没有把相应路径添加到环境变量中    二：文件或函数不存在
> > > > 4. 我这里有python3.7版本 .so 文件，如果你需要的话，我可以发给你。
> > > >    感谢！我编译完的文件还有代码中的问题截图如下：就是编译完会生成so文件，但是代码中的import错误仍在存在。
> > > >    ![Screenshot from 2020-06-30 16-33-19](https://user-images.githubusercontent.com/53289159/86103773-c7304180-baef-11ea-84ce-1a6a7a5ed09f.png)
> > > >    这样是什么问题呢？
> > > 
> > > 
> > > 
> > > 1. 能够确认的是 路径是对的。
> > > 2. 从IDE上面的标记来看，应该是 找不到cython_bbox，而非cython_bbox里的bbox_overlaps。
> > > 3. 应该还是.so 文件的问题,  python 可以直接import   .so 文件，你可以cd 到cython_utils，然后 import cython_bbox 看看错误信息提示是什么，方便进一步debug
> > > 4. 个人的直觉，你可以升级python 版本到3.7试试（建议最新的cython版本），然后再重新删除之前的.so .c 文件，重新编译。
> > 
> > 
> > 感谢！
> > 1.我的数据格式是voc，也就是说每个xml中是xmin，ymin，xmax，ymax。我看在这项目中convert_data_to_tfr_record是用来住转换数据格式的，而且读取的也是voc xml格式。所以，如果转换错了，也应该是这代码中没有进行坐标转换把？(我正在read数据，检查下，而且我确实发现在这代码中转换函数下有给return的格式，如你所说，是四个坐标的值加上标签)
> > 2.看来是我错了？我一直是将自己的类别设为从0开始的哦，而background我知道是要考虑，但是一般不是标记为0.在这里，
> > 我的类别序号是从0开始的，所以我应该重新转换下数据把？而且我怀疑后面的维度错误，是不是也可能跟我这个序号有关系呢？
> > 再次感谢大佬的指点！期待答复和进一步交流，收益很大。
> 
> 不敢妄称大佬，苦逼程序员一枚，正好这些天需要做一些large rotated objects，看到这个，共同学习。
> 建议读下源码，了解下代码结构，方便进一步训练。
> 也可以了解下作者的paper以及知乎的文章，方便进一步学习。

感谢！我昨天试了下，自己写了个坐标转换的脚本，然后程序是可以运行起来，没有报错。
1.但是问题来了，通过tensorboard看学习的情况，heatmap几乎看不到object的feature，然后loss振动很大。
我第一次做遥感的图像目标检测，对于一些参数设置啥的没经验，不知道这种情况是什么问题，该如何调试比较好？
2.所以我在想是不是我转换的数据还是存在问题，如你所说没考虑rotation情况。所以如何判断是不是rotatelabelimg标注的呢，这是个公开的数据集。
3.感谢建议，我也是这么考虑的，开始从源码入手，熟悉每个阶段的工作。另外这个作者的知乎也有关系。
4.我是一个小白，没做过遥感的检测，这个issue学到蛮多的，感谢。

**Comment by ChunmianLin** [comment]
以下是我从tensorboard截图的写结果：总结就是loss震动很大，然后final_detection的映射图是没东西(与ground truth相比)。不知道这种情况我该从哪些方面入手调整呢？
![Screenshot from 2020-07-02 11-35-42](https://user-images.githubusercontent.com/53289159/86313803-961f5080-bc58-11ea-862f-3fd8aa1349b3.png)
![Screenshot from 2020-07-02 11-35-58](https://user-images.githubusercontent.com/53289159/86313807-97e91400-bc58-11ea-9a88-746b887c3593.png)
![Screenshot from 2020-07-02 11-36-22](https://user-images.githubusercontent.com/53289159/86313810-99b2d780-bc58-11ea-9506-7eef7a2b3e45.png)
![Screenshot from 2020-07-02 11-36-54](https://user-images.githubusercontent.com/53289159/86313811-9b7c9b00-bc58-11ea-8745-9018763f5cbf.png)

**Comment by zouxiaoshi** [comment]
1. 没做过 遥感，也没见过上图的heatmap，不知道你用的是哪个训练脚本 目前只用过 multi_gpu_train_r3det
2. loss 震荡，本质上是 不同的batch_sample之间差异大，进而影响权重更新最后传导到Loss.
所以，最简单的是 增大batch_size（目前batch_size是1，好像作者只支持batch_size 1）
其次，调整 optimizer，推荐ADAM，又快又平稳 (也是根据实际情况来调整，我一般都用adam..有点万金油)
最后，适当减小learning rate，加速收敛，也能减少权重更新间的差异。

**Comment by yangxue0827** [comment]
目前除了[r3det的mmdetection 版本](https://github.com/SJTU-Thinklab-Det/r3det-on-mmdetection)，效果更好，训练时间更短，而且支持多gpu和多batch size @ChunmianLin 

ps 看你的日志，你可视化有问题

**Comment by ChunmianLin** [comment]
> 目前出了[r3det的mmdetection 版本](https://github.com/SJTU-Thinklab-Det/r3det-on-mmdetection)，效果更好，训练时间更短，而且支持多gpu和多batch size @ChunmianLin
> 
> ps 看你的日志，你可视化有问题

@yangxue0827 @zouxiaoshi 感谢！
能否具体点说下从我的日志，可视化哪里有问题呢？我不是很明白，我没有修改源码，只是用默认的设置先泡泡看看效果。
对了，我才想起，其实我不是跑这个R2DET，我是在作者@yangxue0827的另一个项目SJTU-Thinklab-Det
/DOTA-DOAI。我看了作者的这几个项目，代码逻辑上是差不多的，就是在模型和一些loss方面做的改进，所以当时就选了一个来跑。抱歉，可能有理解不对的地方。
用的数据集也是遥感数据，目标很小，密集重叠严重。就是不明白效果貌似不是很理想，已经跑了40k step，从tensorboard上看好像还是loss震荡，heatmap看不出啥东西。请问这样情况，下一步该如何进行呢？
