### ISSUE TITLE
DOTA 1.5

### ISSUE THREAD

**Issue by bezero** [Thinklab-SJTU/R3Det_Tensorflow#4]
Have you tested your model on DOTA 1.5. If yes, what are the accuracy results?

**Comment by yangxue0827** [comment]
Sorry i haven't tried on DOTA 1.5
@bezero

**Comment by bezero** [comment]
@yangxue0827 I trained on DOTA 1.5 with the provided config file, the results on Test set:
```
This is your evaluation result for task 1:

mAP: 0.5856237979153807
ap of each class: 
plane:0.75944020837966, 
baseball-diamond:0.6955346564756968, 
bridge:0.43157009782748684, 
ground-track-field:0.5804810415814698, 
small-vehicle:0.41875358047790806, 
large-vehicle:0.6884846599728519, 
ship:0.7091395753325769, 
tennis-court:0.9081168831168833, 
basketball-court:0.7083665242763206, 
storage-tank:0.6510743827687661, 
soccer-ball-field:0.4789450365886169, 
roundabout:0.6351239833789837, 
harbor:0.5551113618038012, 
swimming-pool:0.6297774294133954, 
helicopter:0.4745271636458541, 
container-crane:0.04553418160581875
```

**Comment by yangxue0827** [comment]
Retinanet is not friendly to small targets because P2 is not used.

**Comment by yangxue0827** [comment]
What network configuration do you use?

**Comment by bezero** [comment]
I used default [cfgs.py](https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/master/libs/configs/cfgs.py)

**Comment by yangxue0827** [comment]
The number of containers is very small, and although retinanet used focal loss, it is still not as good as the sampling method of the two-stage method. Apart from this category, there are about 62% mAP, and the results look pretty normal. Data  augumentaion may alleviate this problem. @bezero

**Comment by bezero** [comment]
@yangxue0827 Yes, the results are normal. I just posted them here for reference. And yes, I do agree that if you add data augmentation (rotation, size, ...) and maybe sampling method while training, the results will definitely improve. Thank you for your work and open-sourcing your code!
