### ISSUE TITLE
Doing the large rotated objects detection, hope for some recommendations 

### ISSUE THREAD

**Issue by zouxiaoshi** [Thinklab-SJTU/R3Det_Tensorflow#40]
1. those objects are rotated and relatively large [i.e the target will take 1/3 of the image]
2. I am trying the multi_gpu_train_r3det.py, total loss is like below 0.5, but when I test it by test_dota_r3det.py, it seems no correct annotations shown.

Do I need to adjust the anchor parameters like ratio and scale ? or other methods are suggested to make it better ?

Thx.

**Comment by PC-god** [comment]
mee to. my object is few and large in per image,but it is almost correct in 600*450 img , it is almost bad in 3000*4000 img.
in test , the author split img to different scale sub-img  to net, I don't know what it influence。

**Comment by PC-god** [comment]
我把图片先resize到800*800，再输入到test文件里，效果有质的飞跃。
推理效果除了改输入图片3000*4000到800*800之外，无任何改变。
但是test和train在预处理图片resize是一个原则，怎么会有这样的差异~

**Comment by PC-god** [comment]
我是通过看tensorboard里，image的train时box已经画的很好了，测试时却极差。
看了tensorboard里的img时800*800，就试着在test时先把尺寸固定住，看看效果，如我所料，nice！

**Comment by zouxiaoshi** [comment]
> 我是通过看tensorboard里，image的train时box已经画的很好了，测试时却极差。
> 看了tensorboard里的img时800*800，就试着在test时先把尺寸固定住，看看效果，如我所料，nice！

应该是test 脚本不对，建议用 inference.py 试试。
如果你的是 test_dota 的脚本， 作者会对图片尺寸小于args.h_len 和 args.w_len的部分填充0，args.h_len 和 w_len 默认值是800.
所以。。。你懂得。。。

**Comment by PC-god** [comment]
~脚本不对，用inference立马走向人生巅峰，角度预测的很好

**Comment by yangxue0827** [comment]
test_dota 是用来测DOTA数据集的，DOTA数据集图大需要裁减测试合并结果，一般小图直接用inference.py就行 @PC-god @zouxiaoshi

**Comment by yangxue0827** [comment]
对于DOTA这种大场景的遥感图像，裁图训练必不可少。但是这样会遇到一个矛盾的问题，把图裁小放大对小目标友好（我采用这个做法，小目标数量多），但是会把大目标分成多个部分；把图裁大对大目标比较好，但是小目标可能检测效果会差一些。所以根据你自己需要的情况进行裁剪尺寸的调整吧 @PC-god @zouxiaoshi

**Comment by zouxiaoshi** [comment]
> 对于DOTA这种大场景的遥感图像，裁图训练必不可少。但是这样会遇到一个矛盾的问题，把图裁小放大对小目标友好（我采用这个做法，小目标数量多），但是会把大目标分成多个部分；把图裁大对大目标比较好，但是小目标可能检测效果会差一些。所以根据你自己需要的情况进行裁剪尺寸的调整吧 @PC-god @zouxiaoshi

感觉 feature refinement module 跟 resnet 是一个结构，都是对旧的信息（知识）复合利用。就好比参照旧的笔记来学新的知识。
FPN 整好相反，参考未来的信息（高层feature）来学习低层的特征。 就好比，穿越回到过去，帮助幼时的自己一起学习。
如果再结合 backbone Resnet, 整个模型其实就是时间轴上不同时刻的信息进行复合利用，那么是否存在一种更紧密的方式，重新组织这些信息呢？
