### ISSUE TITLE
可视化

### ISSUE THREAD

**Issue by ChunmianLin** [Thinklab-SJTU/R3Det_Tensorflow#41]
各位好，我在训练那过程可视化检测的结果，感觉结果很奇怪，而且效果好像很不好，请问下各位我这图片都看不到是什么原因呢？
![Screenshot from 2020-07-03 14-12-46](https://user-images.githubusercontent.com/53289159/86437529-49f70d80-bd37-11ea-9acb-fc0dea3c1a50.png)

**Comment by zouxiaoshi** [comment]
如果你没对代码做任何修改的话，大概率是你的数据问题，很有可能对图片进行了某种预处理。还是建议制作完 tf_record之后，读一下tf_record里的数据。
训练的话，multi_gpu__train_r3det.py， 检验的话，test_dota_r3det.py （如果你用的是dota数据集）如果是自己的数据集，inference.py。

**Comment by ChunmianLin** [comment]
感谢！抱歉最近有点事没来得及回复。
请问inference.py是用来做预测的吗？

**Comment by yangxue0827** [comment]
dota数据集（图特别大，需要裁减测试）的话用test_dota.py，一般尺寸比较小的图片测试使用inference.py @ChunmianLin

**Comment by ChunmianLin** [comment]
@yangxue0827 感谢！
我的数据大小，感觉没有到DOTA的水平，基本集中在几个主要尺寸：960×724，1360×800,1920×1280.
我感觉是否没必要进行crop操作呢？而且，我完整试验了一遍，从训练到test，以drop后的数据训练，用test数据集原size进行测试，效果并不好。但如果用train数据集原size直接训练的话，又碰到如下问题，请问这是什么问题呢？（字面意思能看得懂且找得到bug的位置，也尝试print出相关数值， 我的label数是12，所以这里出现54的确不正常。但是我除了改变了下数据其他任何改动都没有，不明白这里报错的原因是什么）
![Screenshot from 2020-07-13 10-04-17](https://user-images.githubusercontent.com/53289159/87263653-6d1c7c80-c4f0-11ea-8e11-37d2166f4726.png)

**Comment by yangxue0827** [comment]
已在另一个issue回复 @ChunmianLin
