### ISSUE TITLE
训练自己的数据

### ISSUE THREAD

**Issue by ChunmianLin** [Thinklab-SJTU/R3Det_Tensorflow#42]
你好，下载好R3Det预训练模型，训练自己的数据，需要调整相应cfg文件中比如freeze之类的操作吗？
我似乎找不到相关的操作命令。(主要是因为下载了预训练模型然后训练，感觉效果并不好，所以在想是不是我只是在trained model上进行微调，而没有freeze backbne进行全部参数的训练呢？)

**Comment by yangxue0827** [comment]
参考这个[参数](https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/master/libs/configs/cfgs.py#L72)

如果你只是在trained model上进行微调的话，可能需要自己修改一下代码才能跑通。

**Comment by ChunmianLin** [comment]
> 参考这个[参数](https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/master/libs/configs/cfgs.py#L72)
> 
> 如果你只是在trained model上进行微调的话，可能需要自己修改一下代码才能跑通。

感谢！后续我再尝试下。
我是否可以理解为：如果在预训练模型基础上，再训练自己的数据，需要调整FREEZE参数来适配模型的维度？

**Comment by yangxue0827** [comment]
如果你要使用我训练好的权重的话，你需要在权重导入的函数做一下修改。原因是类别不一致导致预测层的大小不一致，你需要屏蔽这一层参数的导入就可以了。 @ChunmianLin
