### ISSUE TITLE
预训练模型维度

### ISSUE THREAD

**Issue by ChunmianLin** [Thinklab-SJTU/R3Det_Tensorflow#43]
各位好，我在训练的时候，导入RetinanetDOTA_1X的预训练模型，使用的backbone是resnet50_v1d。运行程序的时候，报下面错误，看字面意思是模型的维度不匹配，这是什么原因导致的呢？我是按作者的config文件夹下相应的retinanet的cfg文件里面的参数，然后下载的模型也是官方的ModelZoo和GloonCV项目中的相应模型，不明白报这个错误的原因，还请各位大佬指点下。感谢！
![Screenshot from 2020-07-11 02-28-45](https://user-images.githubusercontent.com/53289159/87186827-b917c780-c31e-11ea-88f6-47c0e635885e.png)

**Comment by ChunmianLin** [comment]
又试了下同RetinaNet_DOTA_r3det_2x预训练模型，使用的backbone是resnet50_v1d，运行程序同样报错如下，好像跟上面那次报错的维度又不一样，这里我的class_num=12，而原来DOTA的类别数是15，所以这里我该怎么修改呢？(报错信息给的很有限，就显示tf.train.saver()，也就是恢复预训练模型这条命令出问题，所以不知道该怎么解决)
![Screenshot from 2020-07-11 10-42-21](https://user-images.githubusercontent.com/53289159/87214885-3bc27600-c363-11ea-998f-919e24a82887.png)
我总结了下，前后两次我使用的预训练模型、bacbone以及训练命令：
(1) RetinaNet_DOTA_1x_20190531, resnet50_v1d, python multi_gpu_train.py
(2) RetinaNet_DOTA_R3Det_2x_20191118, resnet50_v1d, python multi_gpu_train_r3det.py
还请各位大佬指点，这个问题不知道该如何解决。感谢！

**Comment by yangxue0827** [comment]
修改cfgs.py中的VERSION参数，不然他会加载你下载的trained_weights,由于你是要重投训练，所以只要下载预训练权重resnet50_v1d就行

ps 你需要弄清楚什么是预训练权重（resnet50_v1d）和训练好的权重（RetinaNet_DOTA_r3det_2x） @ChunmianLin

**Comment by ChunmianLin** [comment]
@yangxue0827 感谢答复！
我确实检查了很多遍：VERSION参数、NET_NAME、下载的预训练权重和训练好的权重文件，的对应关系。
我是重新训练自己的数据，所以你的意思是我只需要下载预训练权重resnet50_v1d，而训练好的权重(如RetinaNet_DOTA_R3Det_2x之类的权重文件)没办法使用，对吗？
在您这项目中，没有设置相关freeze的地方吗，就是冻结前半部分的网络结构，不使用最后的预测层之类的设置吗。我主要想能够利用训练好的权重加速模型收敛和学习能力，迁移过来训练我自己的数据。
可能问的问题不太入流，抱歉。
还是谢谢你的回复！
