### ISSUE TITLE
关于R版本的 环境配置

### ISSUE THREAD

**Issue by PC-god** [Thinklab-SJTU/R3Det_Tensorflow#44]
我在tf1.14 cuda10.0，未运行成功R版本。 
错误：Internal: WhereOp
可以提供您的环境么，或者给点建议

**Comment by ChunmianLin** [comment]
@PC-god 你好，从往期的issue，看到您通过预训练模型成功重新训练自己的数据，想请教下导入预训练模型会出现graph维度不匹配的问题吗。如问题#43的问题，我导入预训练模型时候报错了。我检查了很多遍自己下载的预训练模型、所匹配的cfg文件、以及一些必要的参数修改(如类别数、数据集、label_dict等)，但还是没能解决。您有什么好的建议吗？
感谢！

**Comment by PC-god** [comment]
我导入的是resnet50，也就是作者提供的，在导入后 会走restore那部分代码，你在重载的时候 控制台会打印很多参数和梯度，就是构图的变量。 就算成功了。对于不匹配，这个不清楚。
主要还是报错，我经常的错误是rpn或者refine-net里，它是3，4，5，6，7层预测，预测层共享权重，那么在tf里就是  变量域scope resuse= True。
在loss nan，我自己是因为用iou-L1-smooth，改回 L1-smooth，基本就不会出现NAN了，原因不知道。
另一个可以 看 tensorboard，里面加入了训练结果图

**Comment by ChunmianLin** [comment]
@PC-god 感谢！
所以你导入的也是预训练权重(resnet)来训练自己的数据，而不是导入作者在DOTA上的预训练模型(如resnet_DOTA_R3Det之类)来训练，可以这么理解吗。
我同样也比较困惑的就是，在cfg文件中的FREEZE参数，设置了冻结的层数，不太清楚需要怎么修改，才能够直接用作者的预训练模型来训练自己的数据，毕竟这样会收敛更好，效果更好点把(往常经验)。
Loss方面我用的也是L1-Smooth，前期波动比较大，数值一致不稳定且小，到了应该七八万step这样，total loss变NAN了。目前也还没解决这问题。我的数据也是遥感类型数据，所以对于作者原本的一些参数设置没有过多修改，也不明白出现这问题的原因。

**Comment by PC-god** [comment]
~ 没用r3，我就用的retinanet-rotation版本，冻结层 在cfg 里 FIXED_BLOCKS = 1  # allow 0~3  冻结resnet前两层，不训练
这个影响resnet里的冻结层，
loss就不清楚了。而且我不是遥感数据

**Comment by ChunmianLin** [comment]
@PC-god 感谢！我在尝试看看。
