### ISSUE TITLE
模型测试和预测

### ISSUE THREAD

**Issue by ChunmianLin** [Thinklab-SJTU/R3Det_Tensorflow#45]
你好，请问下如何在模型测试时，进行coco类型的mAP计算呢？
还有个问题是如何进行模型预测，得到结果呢？
烦请各位大佬指点下，谢谢！

**Comment by yangxue0827** [comment]
预测参考inference.py，评测的话代码默认是DOTA数据集，如果你需要coco那样的评测需要你自己根据coco评测的api写一个测试脚本
