### ISSUE TITLE
No module named 'help_utils.gaussian_wasserstein_distance'

### ISSUE THREAD

**Issue by smile-ls-all** [Thinklab-SJTU/R3Det_Tensorflow#47]
from help_utils.gaussian_wasserstein_distance import get_element1, get_element4
ModuleNotFoundError: No module named 'help_utils.gaussian_wasserstein_distance'

**Comment by yangxue0827** [comment]
@smile-ls-all update the code

**Comment by smile-ls-all** [comment]
I have updated the code, but the gaussian_wasserstein_distance file cannot be found in the help_util folder

**Comment by smile-ls-all** [comment]
Do you mean your code is still buggy

**Comment by yangxue0827** [comment]
I mean update again.

**Comment by 2018loveyyq** [comment]
I also meet this problem?Have you solved your problem?

**Comment by yangxue0827** [comment]
clone the repo again @2018loveyyq @smile-ls-all

**Comment by 2018loveyyq** [comment]
you mean remove the current repo and redownload it?

**Comment by yangxue0827** [comment]
use 'git pull' command (do not need to remove the current repo)@smile-ls-all @2018loveyyq

**Comment by 2018loveyyq** [comment]
run git pull https://github.com/Thinklab-SJTU/R3Det_Tensorflow.git in the ROOT_PATH?

**Comment by yangxue0827** [comment]
run git pull in the ROOT_PATH

**Comment by 2018loveyyq** [comment]
error: Your local changes to the following files would be overwritten by merge:
        libs/box_utils/iou_rotate.py
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by yangxue0827** [comment]
remove the current repo and redownload it

PS learn more about git

**Comment by 2018loveyyq** [comment]
emmmm
Do it again

**Comment by 2018loveyyq** [comment]
I redownloaded the whole repo and ran it again, but the same error still appeared. I want to know if you have successfully run it, and can you share your complete code with me via email？
