### ISSUE TITLE
NMS on categories

### ISSUE THREAD

**Issue by rai-ss** [Thinklab-SJTU/R3Det_Tensorflow#48]
Thanks for your share. I run you code on my dataset, and inferece it, i find that there maybe several predicted boxes on a target with different categories. The cfgs about NMS is :
```
NMS = True
NMS_IOU_THRESHOLD = 0.05
MAXIMUM_DETECTIONS = 40
FILTERED_SCORE = 0.5
VIS_SCORE = 0.5
```
I guess that you didn't do NMS between different categroies, but it's what I need. So where should I fix?

**Comment by yangxue0827** [comment]
NMS is not required between different categroies. You should first observe whether the confidence threshold is too small. If the confidence between the categories is similar, it means that the model recognition ability is not good. @rai-ss

**Comment by rai-ss** [comment]
> NMS is not required between different categroies. You should first observe whether the confidence threshold is too small. If the confidence between the categories is similar, it means that the model recognition ability is not good. @rai-ss

What if the two different categories has similar shape but I still want to distinguish them. Is it nms an alternative way?
Besides, I want to ask that what's 'FILTERED_SCORE' used in your code. Is it the confidence threshold?

**Comment by yangxue0827** [comment]
FILTERED_SCORE is confidence threshold for visualization. If you do nms between classes, the result may be worse. You may need to improve the classification capabilities of the model to solve your problem.
