### ISSUE TITLE
error: (-215) intersection.size() <= 8 in function rotatedRectangleIntersection

### ISSUE THREAD

**Issue by qingchunlizhi** [Thinklab-SJTU/R3Det_Tensorflow#52]
Hi， When I use the Efficientnet backbone to train the R3Det,  I get this bug after 120k iters:

Traceback (most recent call last):

  File "/home/anaconda2/envs/tensorflow_gpu/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "/R3Det_Tensorflow/libs/box_utils/iou_rotate.py", line 88, in iou_rotate_calculate2
    int_pts = cv2.rotatedRectangleIntersection(r1, r2)[1]

cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/intersection.cpp:247: error: (-215) intersection.size() <= 8 in function rotatedRectangleIntersection

I have checked  the data，it's right. And this is the train loss:
![2020-07-25 22-37-02屏幕截图](https://user-images.githubusercontent.com/18531375/88459469-5569ce80-cec8-11ea-83b5-d45537501ab7.png)

How can I solve this problem. Please give me some advice. Thanks !

**Comment by yangxue0827** [comment]
OPENCV cannot handle iou calculation of rotating bbox with more than 8 intersection points (two overlapping frames).

**Comment by jewelc92** [comment]
I had the same problem, so how to solve it

**Comment by shenqiang-Yuan** [comment]
@jewelc92 updating opencv-python version to 4 makes it work, try it
