### ISSUE TITLE
IMAGE_PYRAMID没有实现？

### ISSUE THREAD

**Issue by Newer2019** [Thinklab-SJTU/R3Det_Tensorflow#53]
数据增强这部分代码没有实现吗？

**Comment by yangxue0827** [comment]
实现了的，https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/master/tools/multi_gpu_train_r3det.py#L131

**Comment by Newer2019** [comment]
短边随机resize一下，相当于只有一张增强的图。
多个尺度的怎么办？比如800*800里面，目标有300*300的，也有600*600的。但是训练集里面只有600*600的样本。

**Comment by Newer2019** [comment]
数据增广的代码，貌似不够完整，影响推理时候结果。
