### ISSUE TITLE
使用最新的代码训练loss还是有nan的情况

### ISSUE THREAD

**Issue by xiaomei1995** [Thinklab-SJTU/R3Det_Tensorflow#54]
![image](https://user-images.githubusercontent.com/45763045/89014619-58d9db80-d348-11ea-91d0-25faa64c8dbd.png)

**Comment by xiaomei1995** [comment]
![image](https://user-images.githubusercontent.com/45763045/89244268-a56b3280-d638-11ea-8113-42a5151d6b27.png)
最新训练的loss曲线

**Comment by PC-god** [comment]
有没有可能是，部分数据错误。

**Comment by ming71** [comment]
我用了杨神的这个overlaps计算的cuda程序也出现过nan，是riou计算那儿的问题。当input boxes出现area为0时，有时候（并不总是）会出现overlap inf的情况，暂时还没找到原因。

**Comment by yangxue0827** [comment]
应该是的，可以加一些判断语句，或者使用别人的riou计算方式替换一下。 @PC-god @ming71 @xiaomei1995

**Comment by yangxue0827** [comment]
有之前出现nan，当时有的预测框的wh接近于0，这个可能导致riou计算出inf，所以还有一种做法就是限制输出框的大小。 @PC-god @ming71 @xiaomei1995

**Comment by ming71** [comment]
我试过几个版本的riou计算，这个cuda加速是最快的，其次是cython，python实现的比如shapely或者opencv就不考虑了，过慢了。如果对速度没那么高的要求可以试试这个cython的[overlaps](https://github.com/ming71/toolbox/tree/master/rotation/overlaps)。
