### ISSUE TITLE
test_dota_r3det_plusplus_ms.py not working

### ISSUE THREAD

**Issue by rampage-rider** [Thinklab-SJTU/R3Det_Tensorflow#55]
I have loaded the pre-trained model in the `output/trained_weights` as shown below
<img width="315" alt="trained weight struct" src="https://user-images.githubusercontent.com/56698590/88832026-cc1b0a80-d1ed-11ea-9f73-2b96e3182349.png">

I have also loaded the pre-trained weights in the `data/pretrained_weights` as shown below
<img width="322" alt="Pre-weights models tree struct" src="https://user-images.githubusercontent.com/56698590/88832085-e81eac00-d1ed-11ea-8e66-6e592d220f94.png">

I have also modified the `cfgs.py` code with the `cfgs_res152_dota_r3det_plusplus_v1.py` code.

Also as per the comments in previous similar issues the code is modified as:
![image](https://user-images.githubusercontent.com/56698590/88834265-37b2a700-d1f1-11ea-92d6-4f4e900323f4.png)

I execute the code using `python test_dota_r3det_plusplus_ms.py --test_dir='../PATH/TO/TEST/DIR/' --gpus=0 -s`

The model runs, but the output images have **no bounding boxes**. Am I doing something wrong?

**Comment by yangxue0827** [comment]
It may be that a lot of bugs have been fixed in the code recently, causing the previously trained weights to not be used normally, so you may need to retrain by yourself. @rampage-rider
