### ISSUE TITLE
Does it support training on non-annotation images?

### ISSUE THREAD

**Issue by JimmyLauren** [Thinklab-SJTU/R3Det_Tensorflow#56]
Hi, thanks for your excellent work. In my case, i encounter background false detection and i don't want to add another label for these false detection. Does it support training on non-annotation images? If not, what modification should i do to make the non-annotation training work?

**Comment by yangxue0827** [comment]
可以给纯背景图片分配一个伪币标签，如[0,0,2,2,1]。这样基本不会被采样到正样本，影响正常训练。
