### ISSUE TITLE
refine feature op coding's question??

### ISSUE THREAD

**Issue by beikeren** [Thinklab-SJTU/R3Det_Tensorflow#57]

**Comment by beikeren** [comment]
In build_whole_network_r3det.py， I have a question about the following code:
        **left_top = tf.cast(tf.transpose(tf.stack([xmin, ymin], axis=0)), tf.int32)
        right_bottom = tf.cast(tf.transpose(tf.stack([xmax, ymax], axis=0)), tf.int32)
        left_bottom = tf.cast(tf.transpose(tf.stack([xmin, ymax], axis=0)), tf.int32)
        right_top = tf.cast(tf.transpose(tf.stack([xmax, ymin], axis=0)), tf.int32)**
I think it should be:
        **left_top = tf.cast(tf.transpose(tf.stack([ymin, xmin], axis=0)), tf.int32)
        right_bottom = tf.cast(tf.transpose(tf.stack([ymax, xmax], axis=0)), tf.int32)
        left_bottom = tf.cast(tf.transpose(tf.stack([ymax, xmin], axis=0)), tf.int32)
        right_top = tf.cast(tf.transpose(tf.stack([ymin, xmax], axis=0)), tf.int32)**
Ther reason is that:
The shape of feature is [H, W], so when we use tf.gather_nd function，Index value [xmin, ymin]  correspond to [W, H], is not [H,W]。
Can you help me to answer this question? Thank you very much!

**Comment by beikeren** [comment]
In build_whole_network_r3det.py， I have a question about the following code:
**left_top = tf.cast(tf.transpose(tf.stack([xmin, ymin], axis=0)), tf.int32)
right_bottom = tf.cast(tf.transpose(tf.stack([xmax, ymax], axis=0)), tf.int32)
left_bottom = tf.cast(tf.transpose(tf.stack([xmin, ymax], axis=0)), tf.int32)
right_top = tf.cast(tf.transpose(tf.stack([xmax, ymin], axis=0)), tf.int32)**
I think it should be:
**left_top = tf.cast(tf.transpose(tf.stack([ymin, xmin], axis=0)), tf.int32)
right_bottom = tf.cast(tf.transpose(tf.stack([ymax, xmax], axis=0)), tf.int32)
left_bottom = tf.cast(tf.transpose(tf.stack([ymax, xmin], axis=0)), tf.int32)
right_top = tf.cast(tf.transpose(tf.stack([ymin, xmax], axis=0)), tf.int32)**
The reason is that:
The shape of feature is [H, W], so when we use tf.gather_nd function，Index value [xmin, ymin] correspond to [W, H], is not [H,W]。
Can you help me to answer this question? Thank you very much!

**Comment by yangxue0827** [comment]
thx, i will check it.

**Comment by yangxue0827** [comment]
After retraining and testing, the effect is similar. @beikeren 

PS: It's very strange why it works before, is it because the fitting ability of backbone automatically transposes the features?
just kidding.
