### ISSUE TITLE
Shape must be rank 0 but is rank 1

### ISSUE THREAD

**Issue by aihyper11** [Thinklab-SJTU/R3Det_Tensorflow#58]
/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 0 but is rank 1 for 'cond/cond/Switch' (op: 'Switch') with input shapes: [7], [7].

During handling of the above exception, another exception occurred:

ValueError: Shape must be rank 0 but is rank 1 for 'cond/cond/Switch' (op: 'Switch') with input shapes: [7], [7].

**Comment by aihyper11** [comment]
tensorflow-gpu==1.13.2

Keras==2.1.6
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5

Packages installed as mentioned in read me file.

**Comment by KwunYat** [comment]
Traceback (most recent call last):
  File "F:/代码/R3Det_Tensorflow-master/libs/box_utils/iou_rotate.py", line 10, in <module>
    from help_utils.gaussian_wasserstein_distance import get_element1, get_element4
ModuleNotFoundError: No module named 'help_utils.gaussian_wasserstein_distance'

**Comment by yangxue0827** [comment]
update the code @KwunYat

**Comment by zhangxiaotao2018** [comment]
问题解决了吗，我测试也遇到同样的问题 @aihyper11

**Comment by leandepk** [comment]
@zhangxiaotao2018 哥们问题解决了吗?我也遇到了相同的问题

**Comment by EatonL** [comment]
@aihyper11 哥们儿，问题好了吗？

**Comment by leandepk** [comment]
没有，后面一直也没解决，总感觉是版本的问题，但是换了好几次版本也没弄好





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Thinklab-SJTU/R3Det_Tensorflow"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月16日(星期三) 下午5:58
收件人:&nbsp;"Thinklab-SJTU/R3Det_Tensorflow"<R3Det_Tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"易伟超"<1413458646@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Thinklab-SJTU/R3Det_Tensorflow] Shape must be rank 0 but is rank 1 (#58)





 
@aihyper11 哥们儿，问题好了吗？

**Comment by EatonL** [comment]
> 
> 没有，后面一直也没解决，总感觉是版本的问题，但是换了好几次版本也没弄好
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Thinklab-SJTU/R3Det_Tensorflow" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月16日(星期三) 下午5:58 收件人:&nbsp;"Thinklab-SJTU/R3Det_Tensorflow"<R3Det_Tensorflow@noreply.github.com&gt;; 抄送:&nbsp;"易伟超"<1413458646@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [Thinklab-SJTU/R3Det_Tensorflow] Shape must be rank 0 but is rank 1 (#58) @aihyper11 哥们儿，问题好了吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我用的docker也是这样，有点无语

**Comment by YYL9404** [comment]
我也遇到这个问题，产生的原因是test_dota_r3det.py 文件下34行调用了 image_preporcess.py 里 short_side_resize_for_inference_data（）函数，继续调用同文件下max_length_limitation（）方法里的tf.cond产生错误，奇怪的是test_dota_r3det.py 文件下32行里的img_batch是tensorflow.python.framework.ops.Tensor object是个一维张量，而比较的对象是一个0维数，这是报错的原因，似乎那个tensorflow.python.framework.ops.Tensor object不能获取到值引发错误的

**Comment by mingmingzhu123** [comment]
采用test*****_ms.py进行测试

**Comment by YYL9404** [comment]
> 采用test*****_ms.py进行测试
还是不行，同样报错

**Comment by wangshaobobetter** [comment]
同样报错了，anaconda3/envs/newtfgpu/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 0 but is rank 1 for 'cond/cond/Switch' (op: 'Switch') with input shapes: [6], [6].

**Comment by yangxue0827** [comment]
更新一下评测脚本，然后试一下下面的命令
![image](https://user-images.githubusercontent.com/29257168/95643816-3b618480-0ae4-11eb-8089-06ca75cc75f4.png)
