### ISSUE TITLE
Different model name in test_dota_r3det.py

### ISSUE THREAD

**Issue by aihyper11** [Thinklab-SJTU/R3Det_Tensorflow#59]
In test_dota_r3det.py:  if cfgs.NET_NAME in ['resnet152_v1d', 'resnet101_v1d', 'resnet50_v1d']:

When downloaded from the link names are represented as: resnet_v1_50.ckpt, resnet_v1_101.ckpt, resnet_v1_152.ckpt

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/89755013-7f4e0280-db10-11ea-9021-72e28f81578c.png)
@aihyper11
