### ISSUE TITLE
errors when testing

### ISSUE THREAD

**Issue by snaillp** [Thinklab-SJTU/R3Det_Tensorflow#6]
I get an error when using test_dota_r3det.py, and the ckpt is saved from training. Can anyone help me? The original error:

Key build_pyramid/build_P3/reduce_dim_P3/biases not found in checkpoint
	 [[node save/RestoreV2 (defined at ../libs/networks/build_whole_network_r3det.py:386)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[{{node save/RestoreV2/_393}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_397_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by yangxue0827** [comment]
you need download trained weights from [here](https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/master/MODEL_ZOO.md).  @snaillp

**Comment by snaillp** [comment]
> you need download trained weights from [here](https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/master/MODEL_ZOO.md). @snaillp

the weight is  trained on my own dataset, do you mean that i should download pretrained weight from the page you gave ?

**Comment by yangxue0827** [comment]
If you have already trained, you do n’t need to download it. Is your training script multi_gpu_train_r3det or you use the same cfgs.py?

@snaillp

**Comment by snaillp** [comment]
> If you have already trained, you do n’t need to download it. Is your training script multi_gpu_train_r3det or you use the same cfgs.py?
> 
> @snaillp

both yes, the config i used is  libs.configs.cfgs, and i change a bit to fit my dataset.

**Comment by yangxue0827** [comment]
It's a little weird. Have you ever run successfully with the weights I've given you? @snaillp

**Comment by snaillp** [comment]
just because the gpu was occupied
