### ISSUE TITLE
map?

### ISSUE THREAD

**Issue by zsh1234567** [Thinklab-SJTU/R3Det_Tensorflow#63]
学长好，请问一下要怎么计算mAP呢

**Comment by yangxue0827** [comment]
DOTA数据集的话，官方有提供评测脚本，我这里只有生成提交结果的脚本。
如果是测自己的数据集的话，参考[hrsc2016的评测脚本](https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/master/tools/test_hrsc2016_r3det.py) @zsh1234567
