### ISSUE TITLE
训练自己的数据集出现问题

### ISSUE THREAD

**Issue by zhangxiaotao2018** [Thinklab-SJTU/R3Det_Tensorflow#65]
你好，感谢开源代码。用您的R3Det训练自己数据集出现如下错误：
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[606] = [25, 5] does not index into param shape [25,25,256]
	 [[{{node tower_0/refine_feature_pyramid/GatherNd_14}}]]
可以帮忙看下原因吗

**Comment by zhangxiaotao2018** [comment]
你好，是训练6000代出现的问题

**Comment by yangxue0827** [comment]
这个错误反馈我也看不出什么问题 @zhangxiaotao2018

**Comment by zhangxiaotao2018** [comment]
好的，谢谢，感觉是参数设置原因

**Comment by lareina115** [comment]
非常感谢开源代码，我也是在训练自己数据集的时候出现这种，help~~~~
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,256,200,200] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node tower_0/resnet50_v1d/C2/bottleneck_1/conv2/BatchNorm/FusedBatchNorm (defined at ..\libs\networks\resnet_gluoncv_r3det.py:110) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by yangxue0827** [comment]
显存不够 @lareina115   out of memory ->OOM

**Comment by zhangxiaotao2018** [comment]
@yangxue0827 你好，测试自己数据集时，用test_ohd-sjtu_r3det.py做简单修改，使用需要注意哪些问题，我测试遇到了这个问题：
Process Process-1:
Traceback (most recent call last):
  File "/home/gyqgyqgyq/anaconda3/envs/Py36_Demo1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1864, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 0 but is rank 1 for 'cond/cond/Switch' (op: 'Switch') with input shapes: [6], [6].

**Comment by zhangxiaotao2018** [comment]
代码中出错的位置在这里：
File "../data/io/image_preprocess.py", line 52, in <lambda>
    max_length_limitation(target_shortside_len * img_w // img_h, length_limitation)),
  File "../data/io/image_preprocess.py", line 16, in max_length_limitation
    false_fn=lambda: length_limitation)

**Comment by yangxue0827** [comment]
IMG_SHORT_SIDE_LEN = 800      cfgs中的参数
如果是多尺度测试，用test_ohd-sjtu_r3det_ms.py @zhangxiaotao2018

**Comment by zhangxiaotao2018** [comment]
没看到这个test_ohd-sjtu_r3det_ms.py @yangxue0827

**Comment by yangxue0827** [comment]
用test_dota_r3det_ms.py @zhangxiaotao2018

**Comment by zhangxiaotao2018** [comment]
好的，thx

**Comment by zhangxiaotao2018** [comment]
你好，不好意思，再请教个问题，我要在较大图像上多尺度测试，例如20000*10000大小的，需要测试时注意哪些问题 @yangxue0827

**Comment by leandepk** [comment]
@yangxue0827 你好，可以请问一下你的数据集是用哪个标注软件做的吗？最近有个项目需要做这个，能加个微信或QQ私聊一下吗

**Comment by PC-god** [comment]
label img，就是用作voc 那个标注软件，你一查就能查到

**Comment by leandepk** [comment]
> label img，就是用作voc 那个标注软件，你一查就能查到

这个可以标注旋转框吗？我之前用都是标注矩形的

**Comment by PC-god** [comment]
嗯，也可以，好像是label img后面的版本，标注人员做的。我没咨询过

**Comment by leandepk** [comment]
> 嗯，也可以，好像是label img后面的版本，标注人员做的。我没咨询过

好的，谢谢您，我去试试看

**Comment by PC-god** [comment]
最好查查。 标注出来的 ，也是xml文件。

**Comment by leandepk** [comment]
> 最好查查。 标注出来的 ，也是xml文件。

嗯嗯，这个代码您复现出来了吗？我复现代码的时候还出了个问题，可以向你请教一下吗

**Comment by PC-god** [comment]
明天吧。我的任务简单。基本是实现了。我没用r3det，而是用的retinanet，直接预测 旋转框

**Comment by leandepk** [comment]
> 明天吧。我的任务简单。基本是实现了。我没用r3det，而是用的retinanet，直接预测 旋转框

行，能加您一个微信吗，我的微信号是18811020656，谢谢啦

**Comment by leandepk** [comment]
你好，最近有时间吗？想向您请教一下关于旋转目标框代码复现的一些细节，希望您的回复





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Thinklab-SJTU/R3Det_Tensorflow"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月6日(星期天) 晚上10:10
收件人:&nbsp;"Thinklab-SJTU/R3Det_Tensorflow"<R3Det_Tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"1413458646"<1413458646@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Thinklab-SJTU/R3Det_Tensorflow] 训练自己的数据集出现问题 (#65)





 明天吧。我的任务简单。基本是实现了。我没用r3det，而是用的retinanet，直接预测 旋转框

**Comment by why228430** [comment]
你好，你是怎么训练自己的数据集的。需要修改哪些代码？@zhangxiaotao2018

**Comment by Boylad** [comment]
> 非常感谢开源代码，我也是在训练自己数据集的时候出现这种，help~~~~
> ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,256,200,200] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
> [[node tower_0/resnet50_v1d/C2/bottleneck_1/conv2/BatchNorm/FusedBatchNorm (defined at ..\libs\networks\resnet_gluoncv_r3det.py:110) ]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

你好，这个解决了吗？
