### ISSUE TITLE
Width and height mix-up

### ISSUE THREAD

**Issue by kriskorrel-cw** [Thinklab-SJTU/R3Det_Tensorflow#66]
Looking at line https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/1d4ba8faf0ed5531e9a0559d8fc733194600e3dd/libs/detection_oprations/anchor_target_layer_without_boxweight.py#L69 (lines 67-70), I'd say that there is an inconsistency in the indexing.
Since `x_c = (anchors[:, 2] + anchors[:, 0]) / 2` (and from other code and comments), I assume that `anchors[:, 0]` are the minimum x values for each anchor, i.e. the left border, while `anchors[:, 2]` represents the right border.
However, subsequently we have that 
`h = anchors[:, 2] - anchors[:, 0] + 1`
I think this should be
`w = anchors[:, 2] - anchors[:, 0] + 1`

Note: I have not run the code. This is just based on code inspection.

**Comment by yangxue0827** [comment]
There is no problem with the code you are referring to. The wh in the two places does not refer to the same thing. @kriskorrel-cw

**Comment by kriskorrel-cw** [comment]
> There is no problem with the code you are referring to. The wh in the two places does not refer to the same thing. @kriskorrel-cw

Sorry, I don't understand. Could you elaborate? To my understanding, these lines of code should convert the anchors in (x1, y1, x2, y2) or (x_min, y_min, x_max, y_max) format to (x_center, y_center, width, height, (theta)) format, but instead converts to  (x_center, y_center, height, width, (theta)) format. Or am I wrong?

**Comment by yangxue0827** [comment]
The w and h in line 69 are related to the opencv default definition box (x, y, w, h, theta). When one (xmin, ymin, xmax, ymax) is converted into a five-parameter representation, the angle is -90 , W refers to the side of the horizontal box parallel to the y axis, that is, w=(ymax-ymin). @kriskorrel-cw

**Comment by yangxue0827** [comment]
You have to be clear about the definition of the box of opencv, the angle range is [-90,0). W specifically refers to the side at an acute angle (including a right angle) with the x-axis. @kriskorrel-cw

**Comment by kriskorrel-cw** [comment]
> You have to be clear about the definition of the box of opencv, the angle range is [-90,0). W specifically refers to the side at an acute angle (including a right angle) with the x-axis. @kriskorrel-cw

👍

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/92390696-f5647a00-f14d-11ea-8704-739c747ca255.png)
@kriskorrel-cw
