### ISSUE TITLE
您好，请问能否在训练中增加负样本，来减少误检？

### ISSUE THREAD

**Issue by CHrcm** [Thinklab-SJTU/R3Det_Tensorflow#69]
1.能否在训练样本中增加不包含目标的负样本数据，已达到在特定应用中较少误检的效果？
2.如果能够增加负样本训练，负样本的标签格式是否为空的xml即可？还是需要特定的处理？

**Comment by yangxue0827** [comment]
你可以给一个伪标签，比如0,0,1,1,0，这样在采样过程中国呢也不会被当成是样本。
