### ISSUE TITLE
伪标签设置

### ISSUE THREAD

**Issue by CHrcm** [Thinklab-SJTU/R3Det_Tensorflow#70]
很高兴看到您对我提出的问题的回复，不过我没有太理解您的意思：
1.如果以DOTA数据为例，每张图片数据经过裁剪后会得到对应的xml标签，其中包含包含每个目标的类别和四个点的坐标值（x1,y1,x2,y2,x3,y3,x3,y4)等相关信息；如果我想自己新增负样本数据，负样本图片不包含目标，其为标签格式需要设置为xml吗？如果是xml的话，其坐标和类别等信息具体该如何设置呢？

**Comment by yangxue0827** [comment]
随便设置一个小一点label框就行，坐标和类别无所谓都可以，只要保证它不会匹配到正样本就行（所以为标签要小） @CHrcm
