### ISSUE TITLE
您好，我的损失在飘动，是因为四点标记的坐标顺序有关吗？

### ISSUE THREAD

**Issue by Wo-Ki** [Thinklab-SJTU/R3Det_Tensorflow#71]
![image](https://user-images.githubusercontent.com/29698317/94632542-794cf480-02fd-11eb-9ddb-2fba43a4a44d.png)

在tensorboard images中，有些也可以检测到，但模型没有保存，请问这是什么问题？

**Comment by yangxue0827** [comment]
多训练会看看有没有预测框出来吧，保存模型的参数都在cfgs.py里 @Wo-Ki
