### ISSUE TITLE
ValueError: Shape must be rank 0 but is rank 1 for 'cond/cond/Switch' (op: 'Switch') with input shapes: [6], [6].

### ISSUE THREAD

**Issue by wangshaobobetter** [Thinklab-SJTU/R3Det_Tensorflow#72]
有人遇到这样的问题吗？

**Comment by wangWilson** [comment]
使用inference 我也遇到了这个问题，使用test_dota_r3det_ms.py测试结果没有bbox

**Comment by yangxue0827** [comment]
更新一下评测脚本，然后试一下下面的命令
![image](https://user-images.githubusercontent.com/29257168/95728132-b7f38f00-0cad-11eb-8df2-77a7640bdf64.png)
@wangshaobobetter @wangWilson
