### ISSUE TITLE
Eval输出的图片应该是怎样的？

### ISSUE THREAD

**Issue by bupt-yfh** [Thinklab-SJTU/R3Det_Tensorflow#73]
执行
python test_dota_r3det_ms.py --test_dir='/PATH/TO/IMAGES/' --gpus=0 --s
生成一个新文件夹test_dota,里面输出测试过后的图片。
可是我经过测试后的图片为啥跟输入的图片一摸一样呢，原本应该是怎样的呢？

**Comment by yangxue0827** [comment]
可能你没有使用训练好的权重，直接用的预训练权重进行测试了 @bupt-yfh

**Comment by wangWilson** [comment]
我也遇到了这个问题,我使用的是DOTA_1836003model.ckpt,也是没有结果,dota的数据集也是没有结果

**Comment by yangxue0827** [comment]
发一下权重放置的路径 @wangWilson

**Comment by wangWilson** [comment]
'R3Det_Tensorflow-master/data/output/RetinaNet_DOTA_R3Det_4x_20200819'  同时也在cfgs.py修改了模型路径

**Comment by yangxue0827** [comment]
R3Det_Tensorflow/tree/master/output/trained_weights/RetinaNet_DOTA_R3Det_4x_20200819
正确路径应该是这样，不然加载不上
@wangWilson

**Comment by wangWilson** [comment]
可以输出框了,是默认TRAINED_CKPT加载不上默认加载与PRETRAINED_CKPT的问题, 谢谢,问题解决了

**Comment by wjfearth** [comment]
> 可以输出框了,是默认TRAINED_CKPT加载不上默认加载与PRETRAINED_CKPT的问题, 谢谢,问题解决了
你好，可以详细讲一下吗？我按照上面所说配置的，然后报错ValueError: Shape must be rank 0 but is rank 1 for 'cond/cond/Switch' (op: 'Switch') with input shapes: [6], [6].，也就连输出都没有。

**Comment by wjfearth** [comment]
> 可以输出框了,是默认TRAINED_CKPT加载不上默认加载与PRETRAINED_CKPT的问题, 谢谢,问题解决了

你好，可以详细讲一下吗？我按照上面所说配置的，然后报错ValueError: Shape must be rank 0 but is rank 1 for 'cond/cond/Switch' (op: 'Switch') with input shapes: [6], [6].，也就连输出都没有

**Comment by wjfearth** [comment]
> R3Det_Tensorflow/output/trained_weights/RetinaNet_DOTA_R3Det_4x_20200819
> 正确路径应该是这样，不然加载不上
> @wangWilson

@yangxue0827 
 杨神，出现这种情况的原因是什么？用的是RetinaNet_DOTA_R3Det_4x_20200819模型
![image](https://github.com/wjfearth/201012/blob/main/2.tif)

**Comment by wjfearth** [comment]
> R3Det_Tensorflow/output/trained_weights/RetinaNet_DOTA_R3Det_4x_20200819
> 正确路径应该是这样，不然加载不上
> @wangWilson

@yangxue0827 
 杨神，出现这种情况的原因是什么？用的是RetinaNet_DOTA_R3Det_4x_20200819模型
![image](https://github.com/wjfearth/20101202/blob/main/error.png)

**Comment by yangxue0827** [comment]
使用的测试命令是什么？ @wjfearth

**Comment by wjfearth** [comment]
> 使用的测试命令是什么？ @wjfearth

!python test_dota_r3det_ms.py --test_dir='../xxxxxx' --gpus=0 -ms -s
