### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by jacksparrow-firstmate** [Thinklab-SJTU/R3Det_Tensorflow#75]
您好
error: Don't know how to compile rbbox_overlaps_kernel.cu to build\temp.win-amd64-3.6\Release\rbbox_overlaps_kernel.obj
出现了这种问题，请问该如何解决

**Comment by yangxue0827** [comment]
你是在windows系统上编译？ @jacksparrow-firstmate

**Comment by nothingws** [comment]
请问下，很苦恼，在windows系统上编译 setup改如何修改呢，

**Comment by yangxue0827** [comment]
https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/issues/50
@jacksparrow-firstmate @nothingws
