### ISSUE TITLE
测试的时候图片的黑边部分总是出现很多检测框，可是那儿并没有物体。

### ISSUE THREAD

**Issue by bupt-yfh** [Thinklab-SJTU/R3Det_Tensorflow#76]
大佬你好，我使用RetinaNet_DOTA_R3Det_4x_20200819模型进行测试。选取了几张dota原数据集里的图片作为输入，输出结果是这样的：
![1](https://user-images.githubusercontent.com/67686114/95807407-ae653800-0d3c-11eb-89cb-1cb76ddf45c9.jpg)
![2](https://user-images.githubusercontent.com/67686114/95807417-b7560980-0d3c-11eb-8b9a-f4217de298e9.jpg)
![3](https://user-images.githubusercontent.com/67686114/95807458-cb017000-0d3c-11eb-89c9-cbe64efaa20d.jpg)
可以看到图片的边缘部分总是检测出一些本不存在的物体。请问你测试的时候也是这样的么？

**Comment by yangxue0827** [comment]
我这现在测试可视化下来也是这样，可能是我代码迭代的时候哪里改了。我还测试了一下这个代码的其他检测器的大权重，就没有这样的问题。
你可以生成一下测试结果提交一下评测系统，以确定是不是代码修改的导致的问题，如果是那就只能重新训练了。 @bupt-yfh
