### ISSUE TITLE
error in coordinate_convert.py

### ISSUE THREAD

**Issue by hongym7** [Thinklab-SJTU/R3Det_Tensorflow#79]
in rect1 = cv2.minAreaRect(box)

error log : 

Unknown: error: /io/opencv/modules/imgproc/src/rotcalipers.cpp:166: error: (-215) orientation != 0 in function rotatingCalipers

i don't know.

error box data is 

[[ 1468923 -1091448]
 [ 2028236 -1430127]
 [-1515439  -915387]
 [ 1696596 -1424113]]

success box data is 

[[   31380  -825436]
 [ 1304903 -1531669]
 [  529444   899271]
 [-1146562 -1537807]]

help me

**Comment by yangxue0827** [comment]
You need to visualize whether this is a valid box.
