### ISSUE TITLE
refine_op

### ISSUE THREAD

**Issue by Vickeyhw** [Thinklab-SJTU/R3Det_Tensorflow#8]
https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/8275ba34c5717b46fd56bfcbd2adcecc0ce3e35e/libs/networks/build_whole_network_r3det.py#L578
这里重构特征图时，只用到了box的中心点，没有用到它的四个角点，感觉和论文里描述的有所不同，不太理解？

**Comment by yangxue0827** [comment]
后来发现用一个点就能达到论文的精度了，所以现在代码只采样一个点了，速度还更快 @Vickeyhw
