### ISSUE TITLE
关于训练速度

### ISSUE THREAD

**Issue by bupt-yfh** [Thinklab-SJTU/R3Det_Tensorflow#80]
RTX2080ti运行指令python multi_gpu_train_r3det.py训练dota数据集。
只使用了两个gpu，可是显存都只使用了155m，远远低于显存上限。
更改--train config里的batchsize也没有用（原本为1)，还是只使用那么多显存。训练的时候step涨的好慢，40个都要接近半小时。我看到global_step有122万。那么请问如何提高训练速度呢？

**Comment by yangxue0827** [comment]
你没有调用到gpu吧，cfgs.py里面设置 @bupt-yfh

**Comment by bupt-yfh** [comment]
我是gpu-group设置的1，2，然后运行训练，然后查看gpu使用率，发现gpu1和gpu2的使用率都不高。

**Comment by bupt-yfh** [comment]
@yangxue0827

**Comment by yangxue0827** [comment]
你有几块gpu

**Comment by bupt-yfh** [comment]
有三块，0，1，2。0那块被别人使用着

**Comment by yangxue0827** [comment]
你是不是安装的是tensorflow不是tensorflow-gpu

**Comment by bupt-yfh** [comment]
我可能得中午回去确认一下

**Comment by bupt-yfh** [comment]
问题解决了，感谢您的回复
