### ISSUE TITLE
关于数据生成data_crop.py

### ISSUE THREAD

**Issue by jewelc92** [Thinklab-SJTU/R3Det_Tensorflow#82]
`box[:, 0] = boxes[:, 0] - top_left_col
                box[:, 2] = boxes[:, 2] - top_left_col
                box[:, 4] = boxes[:, 4] - top_left_col
                box[:, 6] = boxes[:, 6] - top_left_col

                box[:, 1] = boxes[:, 1] - top_left_row
                box[:, 3] = boxes[:, 3] - top_left_row
                box[:, 5] = boxes[:, 5] - top_left_row
                box[:, 7] = boxes[:, 7] - top_left_row
                box[:, 8] = boxes[:, 8]
                center_y = 0.25 * (box[:, 1] + box[:, 3] + box[:, 5] + box[:, 7])
                center_x = 0.25 * (box[:, 0] + box[:, 2] + box[:, 4] + box[:, 6])

                cond1 = np.intersect1d(np.where(center_y[:] >= 0)[0], np.where(center_x[:] >= 0)[0])
                cond2 = np.intersect1d(np.where(center_y[:] <= (bottom_right_row - top_left_row))[0],
                                       np.where(center_x[:] <= (bottom_right_col - top_left_col))[0])

                idx = np.intersect1d(cond1, cond2)`
这部分是/data/io/DOTA/data_crop.py里截取图片的一部分，然后gt坐标也减去左上角坐标的代码，请问最后即使gt框的中心在图片边界内，但是四个边界点的坐标是不是也有可能超出图片边界，这样的框也保留下来是不是会有影响

**Comment by yangxue0827** [comment]
个人感觉只要裁剪的时候有一个的overlap就可以了，边界处理不用太复杂，目标被切割这事无法避免的，只要目标能完整出现在一张子图里就可以了。
