### ISSUE TITLE
训练数据集的格式问题

### ISSUE THREAD

**Issue by huyu6789** [Thinklab-SJTU/R3Det_Tensorflow#83]
![1](https://user-images.githubusercontent.com/46044800/96121197-4cfebe00-0f22-11eb-8033-b7ffe662c975.png)
你好，我在尝试按您写的教程训练自己的数据集时产生了疑惑(这是本人第一次跑模型，所以有些地方不是很熟)，您写的这个第一行VOC_dir的路径是存放自己数据集的什么文件呢，从名字上来看似乎是VOC数据集，但是后面还有image_dir和xml_dir分别代表图片和标注文件。
所以，我想请教一下，要用DOTA数据集重新训练，要做一些什么转换工作吗，我下载了DOTA1.5数据集，它里面就是images(.png文件)和LabelTxt(.txt文件)。

**Comment by yangxue0827** [comment]
按照readme里一步步来就行

**Comment by huyu6789** [comment]
> 按照readme里一步步来就行

谢谢，后面发现用data_crop.py文件可以转换为VOC格式，我现在已经训练生成了权重文件(step：216000,生成了两轮权重文件)，测试也显示加载了权重文件(如下图)，但是输入的图片和输出的图片一摸一样，没有输出框，请问您觉得这种一般是什么情况呢，训练更改的文件都是严格按照您写的readme步骤做的(修改数据集名称，类别，信息等，参数也没有更改过，我用的数据集标注是和DOTA严格一致的，分辨率都为1024x1024)
![1](https://user-images.githubusercontent.com/46044800/96356355-b39cfb00-111f-11eb-8c40-306405fe30b1.png)

**Comment by yangxue0827** [comment]
你先看tensorboard上有结果吗。然后测试时吧置信度阈值调低，才训练这么点一般置信度会比较低

**Comment by huyu6789** [comment]
> 你先看tensorboard上有结果吗。然后测试时吧置信度阈值调低，才训练这么点一般置信度会比较低

tensorboard显示没有文件写入，置信度阈值我调了很低，也是没什么区别。我观察到的一个情况是，loss跳动比较大，几乎都在3和2之间，偶尔会跳动到10甚至更大，会不会是学习率设置的过高导致没有收敛呢？
