### ISSUE TITLE
Learning takes too much time. right?

### ISSUE THREAD

**Issue by hongym7** [Thinklab-SJTU/R3Det_Tensorflow#84]
I have RTX 2080Ti * 2 GPU.
But, elapsed time is very long.
Umm...
Could you noticee me your about elapsed time ?

- elapsed time
- batch size
- gpu
- image size

and so on....

Thank you.

**Comment by yangxue0827** [comment]
do you install tensorflow-gpu?

**Comment by hongym7** [comment]
I resolve this problem.
tensorflow-gpu version
1.15 -> 1.14
maybe cuda version not matched this source.
thank you.
