### ISSUE TITLE
自己的数据训练完成之后的权重文件路径问题

### ISSUE THREAD

**Issue by huyu6789** [Thinklab-SJTU/R3Det_Tensorflow#85]
你好，我今天在生成自己的权重文件之后，默认是放在了R3Det_Tensorflow/output/trained_weights这个路径下面，名字为RetinaNet_game_R3Det_4x_2020101601。然而用test_dota_r3det_ms.py进行测试的时候，发现生成的测试图片无法输出框，请问这种情况是有哪个配置文件我没有修改而导致没有加载我训练生成的权重文件吗？(在别的issue中我发现您特别有强调路径的问题，所以才有此问)

**Comment by yangxue0827** [comment]
训练多久了，可视化的话如果尝试降低置信度阈值

**Comment by huyu6789** [comment]
> 训练多久了，可视化的话如果尝试降低置信度阈值

大概200k次，要了40个小时，一块2080Ti跑的，阈值调到了0.001好像也没用
