### ISSUE TITLE
关于重复框

### ISSUE THREAD

**Issue by bupt-yfh** [Thinklab-SJTU/R3Det_Tensorflow#86]
输出的txt文件里，有很多置信度非常低的框以及重复框。很多图片明明可视化结果里面肉眼只能看到一个框，但是却在txt里面有四行输出。影响了评估结果。请问如何解决这个问题。

**Comment by yangxue0827** [comment]
算mAP不需要卡置信度阈值，所以基本是输出所有预测框。可视化需要卡阈值，建议去看一下mAP的计算原理，以及和用于评价可视化指标F1之间的区别。
