### ISSUE TITLE
训练次数问题

### ISSUE THREAD

**Issue by huyu6789** [Thinklab-SJTU/R3Det_Tensorflow#87]
作者你好，请问使用你们的模型在训练自己的数据集的时候，至少需要训练多少次才能达到一个比较好的效果呢，因为某些原因时间有限，如果按照您repo中示例的那样训练100W次，时间来不及(2080TI训练200k次大概需要40个小时)。关于这一点，您有什么好的建议吗，现在最高训练到200k次，置信度阈值调到0.001也没有任何输出框和坐标。
自己的数据集介绍:2000张图片，分辨率都为1024x1024(使用data_crop.py进行裁剪和数据转换过)，图片格式.png，标注保持和DOTA数据集一致。
ps:附训练40k次的loss图和图片。
![1](https://user-images.githubusercontent.com/46044800/96391555-ba913f80-11eb-11eb-952e-99d047c7088a.png)
![2](https://user-images.githubusercontent.com/46044800/96391556-bbc26c80-11eb-11eb-9005-6804cb6e724a.png)

**Comment by shizhuoyang** [comment]
我也遇到了这个问题，请问你解决了吗？

**Comment by yangxue0827** [comment]
已通过微信解决

**Comment by AITTSMD** [comment]
作者好，我也遇到类似的问题。我训练了17w次，80多轮，输出结果置信度很低，位置也不准确。
