### ISSUE TITLE
请问是否有详细训练自定义数据集的方法

### ISSUE THREAD

**Issue by wuyuanyi135** [Thinklab-SJTU/R3Det_Tensorflow#88]
如题。代码中有许多硬编码的路径，以及一些数据集转换工具的参数似乎无法直接理解参数的意义。请问是否能提供详细的训练一个自己数据集的方法

**Comment by yangxue0827** [comment]
参考https://mp.weixin.qq.com/s/C1pUWBg0LJumNhw20wpqQg

**Comment by wuyuanyi135** [comment]
非常感谢
