### ISSUE TITLE
预测后边框偏移很多

### ISSUE THREAD

**Issue by Blue-Eagle-10** [Thinklab-SJTU/R3Det_Tensorflow#89]
@yangxue0827 @rogerwwww @lygztq @vicFigure @Receiling 
请问：利用r3det训练自己的数据，预测后边框偏移很多，应该从哪个角度去解决？非常感谢！我的数据是1024乘以1024，包含的四个点的坐标

![image](https://user-images.githubusercontent.com/24905967/96444348-b2172400-1240-11eb-9f14-0b9b11258c38.png)

**Comment by yangxue0827** [comment]
你用的命令是什么？

**Comment by Blue-Eagle-10** [comment]
@yangxue0827 谢谢回复！数据导入的部分，我自己编写了导入程度，把原数据集的格式改成了dota的输入格式（我的图片是tif格式）；然后用train. sh训练，用test. sh测试，得到上述结果。我们调试的pytorch版本的r3det，不知道这个问题是否是一样的。谢谢！

**Comment by yangxue0827** [comment]
那你应该去pytorch那个repo反馈，pytorch版本不是我写的 @Blue-Eagle-10
