### ISSUE TITLE
I want to get advice from you

### ISSUE THREAD

**Issue by hongym7** [Thinklab-SJTU/R3Det_Tensorflow#90]
Hello.
I want to get advice from you.

I process about detecting a small ship, large ship, bus, truck and train in aerial image.
Your model is very good.

But....
Car is detected as a small ship
So......  Any good advice?

Thank you very much.

**Comment by yangxue0827** [comment]
Are all cars detected as  small ship? Can you give some examples?

**Comment by hongym7** [comment]
@yangxue0827 

Some cars detected as small ship. (not all)
I can't give you some examples because of security.
I'm so sorry.
So, I give you some example.
train by my data and then inference DOTA dataset.


 
![P0188](https://user-images.githubusercontent.com/3411873/96569109-afc9ce00-1303-11eb-838d-904c3be6b154.png)

**Comment by yangxue0827** [comment]
Their confidence is relatively low and can be filtered by setting a threshold. Of course the model will not be able to detect them. This may be that their scale is too small, and the scale of your training set is relatively large.

**Comment by hongym7** [comment]
@yangxue0827 
Thank you your advice.
This method cannot be used because even a correct small ship has low confidence.

**Comment by hongym7** [comment]
@yangxue0827 

One more question.
What is the effective post processing?
For example
1. (width/height ratio > 1.2 ) in car, ship class
2. and so on.....

Thank you.

**Comment by yangxue0827** [comment]
You need to try this yourself
