### ISSUE TITLE
测试没有检测结果

### ISSUE THREAD

**Issue by chongkuiqi** [Thinklab-SJTU/R3Det_Tensorflow#94]
大家好！感谢作者的分享！
    我使用了DOTA的训练数据对模型进行测试，发现resnet152_v1d还有其它几个模型都没有任何检测结果，输出的图像上没有检测框，生成的txt结果文件也没有任何内容，我查看了test_net代码，没有发现任何问题，请问我该从哪几个方面来考虑这个问题呢？

**Comment by yangxue0827** [comment]
确认一下是否下载了训练好的权重，以及摆放的位置是否正确。你可以把权重的路径贴到这里来，帮你看一下。

**Comment by chongkuiqi** [comment]
> 确认一下是否下载了训练好的权重，以及摆放的位置是否正确。你可以把权重的路径贴到这里来，帮你看一下。
感谢您的解答。我的权重位置如下：

![Selection_001](https://user-images.githubusercontent.com/46895488/97083586-95655c80-1643-11eb-96ef-e7fca9bb39df.png)

**Comment by yangxue0827** [comment]
你这个是预训练权重，用来训练的

**Comment by chongkuiqi** [comment]
> 你这个是预训练权重，用来训练的

请问下面这个模型是不是训练好的权重，是不是下载它之后，改名为resnet152_v1d，然后在放入./pretrain_weights/下，进行测试？
![image](https://user-images.githubusercontent.com/46895488/97084210-145c9400-1648-11eb-8a6a-2f98ffe82942.png)

**Comment by yangxue0827** [comment]
下载下来直接解压放到output/trained_weight下面

**Comment by chongkuiqi** [comment]
> 下载下来直接解压放到output/trained_weights
非常感谢您的解答，但还是会报错如下，无法在pretrain_weights下找到resnet152_v1d.ckpt，
![image](https://user-images.githubusercontent.com/46895488/97084610-dad95800-164a-11eb-9397-37ea303b952d.png)
但在pretrain_weights下添加resnet152_v1d.ckpt后，还是不会输出检测结果，我使用的测试命令如下， ../test是我放测试图像的路径
![image](https://user-images.githubusercontent.com/46895488/97084587-b7161200-164a-11eb-92c5-c60329005364.png)

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/97084757-d497ab80-164b-11eb-8be7-db8ffad71279.png)
参考这个路径

**Comment by chongkuiqi** [comment]
> ![image](https://user-images.githubusercontent.com/29257168/97084757-d497ab80-164b-11eb-8be7-db8ffad71279.png)
> 参考这个路径
谢谢！问题已解决！！！十分感谢您耐心的解答！！！
