### ISSUE TITLE
测试输出没有类别、置信度和四点坐标信息的txt文件

### ISSUE THREAD

**Issue by Blue-Eagle-10** [Thinklab-SJTU/R3Det_Tensorflow#96]
@yangxue0827 
感谢分享！
我利用自己的数据集做的训练，然后运行R3Det_Tensorflow-master\tools\test_dota_r3det_ms.py文件测试，测试之后只有输出测试图片，并没有相关的类别、置信度和四点坐标信息的txt文件，请问一下，是哪里设置有问题么？
![image](https://user-images.githubusercontent.com/24905967/97183449-c32fda00-17d8-11eb-8fc8-a04a01a6cee4.png)
![image](https://user-images.githubusercontent.com/24905967/97183476-ccb94200-17d8-11eb-8bbb-9e9acbf3a73b.png)

**Comment by peiwenYe** [comment]
需要把--show_box设置为False

**Comment by yangxue0827** [comment]
测试命令不要加-s
