### ISSUE TITLE
小目标漏检

### ISSUE THREAD

**Issue by peiwenYe** [Thinklab-SJTU/R3Det_Tensorflow#97]
大佬您好，我训练出来发现小目标的检测效果不太好，我把Anchor的level增加了p2，并且把包含小目标的训练数据重复了一次。但是效果仍然不是很理想。请问您有什么改进的建议吗？望指教。

**Comment by yangxue0827** [comment]
你把你改的地方贴一下

**Comment by peiwenYe** [comment]
谢谢回复~
`# ---------------------------------------------Anchor config
LEVEL = ['P2', 'P3', 'P4', 'P5', 'P6', 'P7']
BASE_ANCHOR_SIZE_LIST = [20, 32, 64, 128, 256, 512]
ANCHOR_STRIDE = [4, 8, 16, 32, 64, 128]
ANCHOR_SCALES = [2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]
ANCHOR_RATIOS = [1, 1 / 2., 2., 1 / 3., 3., 1 / 5., 5.]
ANCHOR_ANGLES = [-90, -75, -60, -45, -30, -15]
ANCHOR_SCALE_FACTORS = None
USE_CENTER_OFFSET = True
METHOD = 'H'
USE_ANGLE_COND = False
ANGLE_RANGE = 90
`
主要是改的anchor设置这部分，数据集增强除了把cfgs.py里面的设置改为True之外，策略是手动把小目标比较多的挑选出来重复一次加到原来的数据里面，因为我们的数据集数量比较少。

**Comment by yangxue0827** [comment]
tensorboard中小目标的positive anchor多吗

**Comment by peiwenYe** [comment]
多

**Comment by peiwenYe** [comment]
多，但是也不全，部分小目标没有positive anchor

**Comment by yangxue0827** [comment]
能贴个图例吗，看看多小

**Comment by peiwenYe** [comment]
![QQ图片20201030094507](https://user-images.githubusercontent.com/37332773/97650463-ae7f6a80-1a94-11eb-9755-20707f1c1f28.png)
大概是10个像素大小的小目标检测不到

**Comment by yangxue0827** [comment]
你可以把图放大来提高小目标的大小，设置cfgs.py中的IMG_SHORT_SIDE_LEN参数

**Comment by yangxue0827** [comment]
另外效果不好你是怎么比的，适合其他方法比较还是就看一个r3det的评测结果

**Comment by peiwenYe** [comment]
我是计算mAP比较的，还把test的结果show_box和真实标签比较，也发现漏了很多小目标。另外IMG_SHORT_SIDE_LEN我是IMG_SHORT_SIDE_LEN = [800, 400, 600, 700, 900, 1000, 1100, 1200]这样设置的。

**Comment by yangxue0827** [comment]
你这样比较不客观，单纯看一个结果不能说这个方法的好坏，需要和其他想法比较或者你比较加入P2之后有没有改善。毕竟小目标本身是难点，你不能指望他的指标和大目标一样高才算是效果好。

**Comment by peiwenYe** [comment]
收到！我回头做一个对比分析，非常谢谢大佬百忙之中回复我~
