### ISSUE TITLE
refine_reg_loss_stage3

### ISSUE THREAD

**Issue by wxjbagwq** [Thinklab-SJTU/R3Det_Tensorflow#98]
请问一下训练时候的refine_reg_loss_stage3代表什么意思呢？它和refine_reg_loss的区别在哪里？另外一个问题就是cfgs.py中ANCHOR_RATIOS和ANCHOR_SCALES可以增加吗？

**Comment by yangxue0827** [comment]
1. refine_reg_loss_stage3表示第二个refine阶段，和cfgs.py里的NUM_REFINE_STAGE有关
2. ANCHOR_RATIOS和ANCHOR_SCALES可以自己设置

**Comment by wxjbagwq** [comment]
谢谢！这里还有一些不太明白的地方：
1. 默认NUM_REFINE_STAGE为1的时候是否就代表没有refine_reg_loss_stage3存在，全为0就是正常的？
2. 我将rpn阶段refine的positive的阈值调整得很低，才得到若干positive anchor，请问这样对inference会有影响吗？另外，refine positive threshold需要调整吗？

**Comment by yangxue0827** [comment]
1. 设置成1说明只有一个refine阶段，所以后面那个是0是正常的。
2. refine阶段的采样阈值不能比上一阶段低，不然没有意义了。refine阶段采样到正样本的前提是上一阶段训练的比较好了，所以刚开始refine阶段没有正样本是正常的，他在等上一阶段提供稳定的候选框。如果一直没有，说明前面阶段就没有训练好，网络训练就存在问题。

**Comment by wxjbagwq** [comment]
1. 那这是否意味着在保证采样到较多refine阶段正样本的情况下可以逐步提高采样阈值？
2. 我正在训练HRSC2016，能不能参考一下你训练它时候的cfgs.py？

**Comment by yangxue0827** [comment]
我的采样阈值就是逐步提高的，这个也是refine的目的。cfgs用DOTA那个就行，我没有怎么改。

**Comment by wxjbagwq** [comment]
原来如此，谢谢回答！
目前我正在训练，在没有分配anchor的地方有时会错误地检测出目标，这是因为我的采样阈值较低而造成的吗？有没有什么办法可以避免的？

**Comment by yangxue0827** [comment]
小目标采样不到很正常
