### ISSUE TITLE
R3det++对大的物体识别效果

### ISSUE THREAD

**Issue by kangkau** [Thinklab-SJTU/R3Det_Tensorflow#99]
您好，在r3det和r3det++上同样配置训练了相同的轮数，r3det++效果反而不如r3det, 某一类大的物体ap出现了0, 可视化后发现bounding box几乎都只框了一部分，或者框的是没有物体的背景，想请教您一下可能的原因，非常感谢！

**Comment by yangxue0827** [comment]
那应该是训练出问题了，出现0不正常，测试脚本用对了吗？

**Comment by kangkau** [comment]
后来试了一下前面保存的模型，ap有所上升，但那个大物体的类ap只到了4%，用r3det时远高于这个，所以有点不解，r3det++比它改变在什么地方了呢？

**Comment by yangxue0827** [comment]
只有4%肯定是训练有问题了，所以不需要从方法上区分析。
